### ISSUE TITLE
player.hasPermission() > null pointer

### ISSUE THREAD

**Issue by mmonkey** [SpongePowered/SpongeCommon#117]
I get a null pointer error when checking player.hasPermission("warp.admin").

using sponge build 533, forge 1499 in single player.

Also, I am not using a permission plugin of any kind.

**Comment by zml2008** [comment]
Post the stacktrace...

**Comment by mrgoodrich** [comment]
Speaking of which, @zml2008 is it better to post question in a git issue or on the forums?  I want to do what is the most convenient for those who will likely answer.

**Comment by zml2008** [comment]
@mrgoodrich for Sponge bugs, post on GH, especially if you can provide useful corroborating information -- this is where most of us go to look for issues, and what is linked to more people's email, and is more directly connected with actual code changes.

**Comment by mmonkey** [comment]
```
[01:05:45] [Server thread/FATAL] [FML/]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.UserListOps.func_152699_b(SourceFile:39) ~[sp.class:?]
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9) ~[sp.class:?]
	at net.minecraft.server.management.UserList.func_152683_b(SourceFile:56) ~[ss.class:?]
	at org.spongepowered.common.service.permission.UserSubject.getOpLevel(UserSubject.java:93) ~[UserSubject.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at org.spongepowered.common.service.permission.UserSubject$1.getParent(UserSubject.java:55) ~[UserSubject$1.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at org.spongepowered.common.service.permission.base.SingleParentMemorySubjectData.getParents(SingleParentMemorySubjectData.java:51) ~[SingleParentMemorySubjectData.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getDataPermissionValue(SpongeSubject.java:65) ~[SpongeSubject.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getPermissionValue(SpongeSubject.java:58) ~[SpongeSubject.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at org.spongepowered.common.service.permission.UserSubject.getPermissionValue(UserSubject.java:115) ~[UserSubject.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at net.minecraft.entity.player.EntityPlayerMP.getPermissionValue(EntityPlayerMP.java:147) ~[qw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:129) ~[qw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:141) ~[qw.class:?]
	at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:279) ~[SimpleCommandService.class:1.8-1499-2.1DEV-533+unknown-b533.git-unknown]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) ~[cl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) ~[rj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) ~[rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) ~[lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) ~[lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
```

**Comment by mmonkey** [comment]
I actually get this error when running any command that checks permissions (/time set day)

**Comment by zml2008** [comment]
Are you running the server in offline mode?

**Comment by mmonkey** [comment]
no, I am just running in single player worlds.

**Comment by zml2008** [comment]
is the client running in offline mode? But yeah, this issue has been seen before, and seems to be an issue with game profile resolution clientside -- @simon816 changed that code recently.

**Comment by bloodmc** [comment]
This issue can be caused by 2 things:

1. Running the client in offline mode which we will not support.
2. Mojang auth server temporarily blocking your request for GameProfile properties on login. This is what you would see in log 

[12:37:02] [pool-4-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@a1d2215[id=uuid,name=UserName,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time

If this occurs, simply wait a minute and try again to make sure you do not receive this error.

**Comment by ST-DDT** [comment]
Is this exception happening client side or server side?
I'm asking because of this:

> Running the client in offline mode which we will not support.

Developing and testing plugins is quite hard if you only have one player, i usually use offline mode to allow my test players to connect and interact with the world (and i don't want to buy more accounts just for testing purposes). I don't need real/full offline support, but at least it should not throw an exception everytime i try to do anything. Testing an arena plugin is impossible with just one player.

**Comment by JBYoshi** [comment]
@ST-DDT mmonkey said he "was just running in singleplayer worlds". Based on the stack trace, it's on the server thread.

**Comment by ST-DDT** [comment]
Okay, I got that from the stack trace as well, but i wasnt sure which one.
I just thought it would affect dedicated servers as well.

**Comment by bloodmc** [comment]
@ST-DDT agreed, I'll look into a fix for testing purposes.

**Comment by simon816** [comment]
I think I know what's happening here

It's because forge has used up the request limit for a player's profile. The session service limits to once per UUID per minute.
In fact, forge actually surpasses the limit and suffers `The client has sent too many requests within a certain amount of time` itself.
Due to the changes in https://github.com/MinecraftForge/MinecraftForge/pull/1832, the game makes a request to fill the game profile, but uses the _secure_ flag, which means the response isn't cached.
Later on (but less than a minute) the `SkinManager` makes a request, but this fails due to the limit.
Adding sponge to the mix, a third request is also made.
The first request adds the profile as the `Minecraft.getMinecraft().getSession()` profile.
What I can do is fix forge by using that profile instead (because it's already been filled), and add a special case to sponge in `SpongeProfileResolver` to use the session profile if on client and if requesting the client's profile.

**Comment by JBYoshi** [comment]
I've been looking into this, and I've found it to happen:
- When "`The client has sent too many requests in a certain amount of time`", as mentioned above
- When *the client is running without being properly authenticated* (as it is when rinning it from development), OR **on the dedicated server** *when it is in offline mode*. In this case, the failure is `profile.isComplete()` returning `false` at https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/service/profile/SpongeProfileResolver.java#L75.
