### ISSUE TITLE
Issue with MixinText

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#142]
I encountered this when testing #100, but as I don't change `MixinText`, I'm going to pass it off to SpongeCommon.

```
[16:57:07] [Client thread/WARN] [mixin]: Mixin failed applying mixins.common.api.json:text.MixinText -> org.spongepowered.api.text.Text: org.spongepowered.asm.mixin.transformer.InvalidMixinException Shadow field color was not located in the target class
org.spongepowered.asm.mixin.transformer.InvalidMixinException: Shadow field color was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attachFields(MixinPreProcessor.java:222) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.attach(MixinPreProcessor.java:151) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessor.createContextFor(MixinPreProcessor.java:133) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:511) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicator.apply(MixinApplicator.java:189) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:594) ~[mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:566) [mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:402) [mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:104) [mixin-0.4.4-SNAPSHOT.jar:0.4.4-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_45]
	at java.lang.Class.getDeclaredMethods0(Native Method) [?:1.8.0_45]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) [?:1.8.0_45]
	at java.lang.Class.getDeclaredMethod(Class.java:2128) [?:1.8.0_45]
	at org.spongepowered.mod.event.SpongeModEventManager.buildFactoryMethodMappings(SpongeModEventManager.java:139) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.<init>(SpongeModEventManager.java:132) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager$$FastClassByGuice$$7686990d.newInstance(<generated>) [$ReflectUtils.class:?]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) [$FastConstructor.class:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) [DefaultConstructionProxyFactory$1.class:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [ConstructorBindingImpl$Factory.class:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) [FactoryProxy.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [ProviderToInternalFactoryAdapter$1.class:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [InjectorImpl.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [ProviderToInternalFactoryAdapter.class:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [SingletonScope$1.class:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [InternalFactoryToProviderAdapter.class:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) [SingleParameterInjector.class:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) [SingleParameterInjector.class:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [ConstructorBindingImpl$Factory.class:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) [FactoryProxy.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [ProviderToInternalFactoryAdapter$1.class:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [InjectorImpl.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [ProviderToInternalFactoryAdapter.class:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [SingletonScope$1.class:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [InternalFactoryToProviderAdapter.class:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) [SingleParameterInjector.class:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) [SingleParameterInjector.class:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) [ConstructorInjector.class:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) [ConstructorBindingImpl$Factory.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [ProviderToInternalFactoryAdapter$1.class:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) [InjectorImpl.class:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [ProviderToInternalFactoryAdapter.class:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145) [SingletonScope$1.class:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) [InternalFactoryToProviderAdapter.class:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) [InjectorImpl$2$1.class:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) [InjectorImpl.class:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) [InjectorImpl$2.class:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) [InjectorImpl.class:?]
	at org.spongepowered.mod.SpongeMod.<init>(SpongeMod.java:102) [SpongeMod.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_45]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_45]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_45]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_45]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:446) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
	at jbyoshi.mcdev.GameLauncher.callMain(GameLauncher.java:86) [bin/:?]
	at jbyoshi.mcdev.GameLauncher.access$0(GameLauncher.java:53) [bin/:?]
	at jbyoshi.mcdev.GameLauncher$1.run(GameLauncher.java:59) [bin/:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

Current commits (before my changes):
- SpongePowered/SpongeAPI@96ba8cb40d54508ce346ed04290442bdfe12ab9d
- SpongePowered/SpongeCommon@9c5b21378c7e3c9069ae1421cc72d4fc86ba38bb
- SpongePowered/Sponge@e2b4a082451aa1b30b86357b137a51a076e9d364

Probably related to the changes in SpongePowered/SpongeAPI@0b1cf1f77c82adb2bb345efd97247eb91260165d.

**Comment by JBYoshi** [comment]
Updated to the latest commits. This still occurs.
- SpongePowered/SpongeAPI@f164da66e3d0294f30379810ad9b82afa798a519
- SpongePowered/SpongeCommon@d2d3b90f263760657118dc58ccd1e92024adbc3e

**Comment by JBYoshi** [comment]
Thanks! I'll go import that and continue testing.
