### ISSUE TITLE
Internal Exception: java.lang.NoClassDefFoundError: Could not initialize class org.spongepowered.api.event.SpongeEventFactoryUtils

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#158]
When I try to load a world, I get stuck on the main menu. The first tile you try to log in, the log displays `[08:55:54] [Server thread/INFO]: com.mojang.authlib.GameProfile@20bd291a[...] (local:E:bc712f6a) lost connection: Internal Exception: java.lang.NoClassDefFoundError: org/spongepowered/api/eventgencore/PropertySearchStrategy`. (Afterwards, it gives a much less helpful exception with a recursive cause. Let me know if you need it.) I was able to use the debugger to get the stack trace:
```
java.lang.NoClassDefFoundError: org/spongepowered/api/eventgencore/PropertySearchStrategy
    at org.spongepowered.api.util.event.factory.ClassGeneratorProvider.<init>(ClassGeneratorProvider.java:40)
    at org.spongepowered.api.event.SpongeEventFactoryUtils.<clinit>(SpongeEventFactoryUtils.java:53)
    at org.spongepowered.api.event.SpongeEventFactory.createClientConnectionEventAuth(SpongeEventFactory.java:3284)
    at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEvent(NetHandlerLoginServer.java:145)
    at net.minecraft.server.network.NetHandlerLoginServer.fireAuthEventOffline(NetHandlerLoginServer.java:157)
    at net.minecraft.server.network.NetHandlerLoginServer.processLoginStart(NetHandlerLoginServer.java:149)
    at net.minecraft.network.login.client.C00PacketLoginStart.processPacket(C00PacketLoginStart.java:41)
    at net.minecraft.network.login.client.C00PacketLoginStart.processPacket(C00PacketLoginStart.java:54)
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:144)
    at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:469)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
    at io.netty.channel.local.LocalChannel.finishPeerRead(LocalChannel.java:312)
    at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:44)
    at io.netty.channel.local.LocalChannel$6.run(LocalChannel.java:298)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.eventgencore.PropertySearchStrategy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 21 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 23 more
```

I do have `event-gen-core` on my build path. What's going on?

**Comment by Aaron1011** [comment]
This should be fixed in https://github.com/SpongePowered/Sponge/commit/4766778d6a2b35c8bef85afee5737efcb188f74d.

**Comment by JBYoshi** [comment]
Never mind. I just needed to re-add my Eclipse run configuration.

**Comment by ST-DDT** [comment]
The gradle refresh dependency menu entry does this quite well.

**Comment by JBYoshi** [comment]
Maybe I should check out the Gradle Eclipse plugin. :smile:
