### ISSUE TITLE
Add world limit protection measures

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#168]
So, currently you can teleport beyond the limits of Minecraft if using the API. I don't believe this should be possible, and I think we probably shouldn't be crashing like this if someone manages to go beyond the generate-able world:

``` java
net.minecraft.util.ReportedException: Exception generating new chunk
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:699) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:47) ~[minecraft_server.1.8.jar:?]
        at net.minecraft.world.chunk.Chunk.onConstructed(Chunk.java:88) ~[bfh.class:?]
        at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:93) ~[bfh.class:?]
        at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:97) ~[bfh.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:256) ~[bgv.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:162) ~[qs.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:122) ~[qs.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:92) ~[qs.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:189) ~[qs.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:304) ~[aqu.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:380) ~[qt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by ST-DDT** [comment]
Which limits? World border, beyond far lands?
Could you post the teleport command/params?

> I don't believe this should be possible

I agree on this, this should throw in `IllegalArgumentException` in that case.

**Comment by DarkArc** [comment]
Well, the far lands were removed in Beta 1.8. However, there is a game engine limitation of X/Z: ±30,000,000, which we are breaking if chunks past that point are requested.

**Comment by JBYoshi** [comment]
@DarkArc Vanilla actually does generate chunks past that limit; players can't enter them, however. The real limit is 33,554,432 for each (X and Z) based on calculations from `BlockPos`.

**Comment by DarkArc** [comment]
Well I was just going off of what the MC wiki detailed to be the limit.

**Comment by MoeBoy76** [comment]
if a non-creative player goes outside the border they get insta-killed and creative players are unable to interact with anything but chunk loading could be a problem if players start loading chunks outside the border

**Comment by ryantheleach** [comment]
I just checked this in vanilla 1.8.8 for the record. http://puu.sh/kdr46/cbf0e43626.jpg

Teleporting to 29 999 999 ~ 29 999 999 teleported me outside the default world border, which appeared at 29999983 ~ 29999983.

Nor did terrain generate beyond that point. http://puu.sh/kdrf8/43e4156e9d.jpg

This was done using a superflat world with the redstone ready preset, in case this changes things.
