### ISSUE TITLE
Entitys removed for bounding box restrictions crash server

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeCommon#198]
Produced by making a size 20+ slime
```

[20:55:13] [Server thread/WARN] [Sponge]: Entity being removed for bounding box restrictions
[20:55:13] [Server thread/WARN] [Sponge]: BB Size: 140,608 > 1,000 avg edge: 51.007
[20:55:13] [Server thread/WARN] [Sponge]: Motion: (0, 0, 0.02)
[20:55:13] [Server thread/WARN] [Sponge]: Calculated bounding box: box[258.41554272254206, 73.1453049667193, 962.535388776384 -> 309.4155465372393, 124.14530878141656, 1013.5553925887716]
[20:55:13] [Server thread/WARN] [Sponge]: Entity bounding box: null
[20:55:13] [Server thread/WARN] [Sponge]: Entity: EntitySlime['Slime'/548, l='world', x=283.92, y=73.15, z=988.04]
[20:55:13] [Server thread/WARN] [Sponge]: Entity NBT: {HurtByTimestamp:0,ForgeData:{SpongeData:{maxAir:300,Creator:{uuid_most:552399715290140065L,uuid_least:-5550302215138226918L,},},},Size:99,Attributes:[0:{Base:10000.0d,Name:"generic.maxHealth",},1:{Base:0.0d,Name:"generic.knockbackResistance",},2:{Base:10.199999809265137d,Name:"generic.movementSpeed",},3:{Base:16.0d,Name:"generic.followRange",},],Invulnerable:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,DropChances:[0:0.085f,1:0.085f,2:0.085f,3:0.085f,4:0.085f,],PersistenceRequired:0b,HealF:10000.0f,Motion:[0:0.0d,1:0.0d,2:0.019999997690320015d,],wasOnGround:0b,Leashed:0b,UUIDLeast:-5992112659810672749L,Health:10000s,Air:300s,OnGround:0b,Dimension:0,Rotation:[0:0.0f,1:0.0f,],UUIDMost:857056644399910375L,Equipment:[0:{},1:{},2:{},3:{},4:{},],Pos:[0:283.9155446298907d,1:73.1453049667193d,2:988.0353906837327d,],Fire:0s,CanPickUpLoot:0b,HurtTime:0s,}
[20:55:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:781) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:385) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: org.spongepowered.asm.mixin.injection.callback.CancellationException: The call getCollidingBoundingBoxes is not cancellable.
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfo.cancel(CallbackInfo.java:100) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.setReturnValue(CallbackInfoReturnable.java:105) ~[mixin-0.4.6-SNAPSHOT.jar:0.4.6-SNAPSHOT+unknown-b0.git-unknown]
	at net.minecraft.world.World.onGetCollidingBoundingBoxes(World.java:254) ~[World.class:?]
	at net.minecraft.world.World.getCollidingBoundingBoxes(World.java) ~[World.class:?]
	at net.minecraft.entity.Entity.moveEntity(Entity.java:639) ~[Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.moveEntityWithHeading(EntityLivingBase.java:1709) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2036) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:452) ~[EntityLiving.class:?]
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:1838) ~[EntityLivingBase.class:?]
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:276) ~[EntityLiving.class:?]
	at net.minecraft.entity.monster.EntitySlime.onUpdate(EntitySlime.java:125) ~[EntitySlime.class:?]
	at net.minecraft.world.World.onCallEntityUpdate(World.java:341) ~[World.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2034) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:758) ~[WorldServer.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2000) ~[World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1826) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:587) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:775) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by JBYoshi** [comment]
Well, that's an easy fix... someone just forgot to add `cancellable = true` to the annotation on line 249.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/7bab2983e3417000b35cff822a0f2946a496c369

**Comment by ssjgodbluegogeta** [comment]
i have the same problem but dont understand how to fix it

**Comment by ryantheleach** [comment]
@ssjgodbluegogeta It's extremely unlikely you have exactly the same issue as one from 3 years ago.

Please open a new ticket, (referencing this one if you truly think it's related) With logs, reproduction steps, modlist etc.
