### ISSUE TITLE
Post tick captures are applying properties on the incorrect blocktype.

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#237]
```
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class thaumcraft.common.blocks.world.eldritch.BlockEldritch$EldritchType, values=[altar, cap, obelisk_base, obelisk_body, lock, door, teleporter, crabspawner]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:174) ~[BlockState$StateImplementation.class:?]
	at thaumcraft.common.blocks.world.eldritch.BlockEldritch.getMetaFromState(BlockEldritch.java:135) ~[BlockEldritch.class:?]
	at net.minecraft.block.Block.getHarvestTool(Block.java:2218) ~[Block.class:?]
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:132) ~[ForgeHooks.class:?]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:82) ~[BlockEvent$BreakEvent.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockBreakEvent(SpongeForgeEventFactory.java:783) ~[SpongeForgeEventFactory.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:309) ~[SpongeForgeEventFactory.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:201) ~[SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) ~[SpongeModEventManager.class:?]
	at net.minecraft.world.World.handlePostTickCaptures(World.java:806) ~[World.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(PacketThreadUtil.java:60) ~[PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:24) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
```

**Comment by Zidane** [comment]
The above came from Thaumcraft 5.

**Comment by liach** [comment]
Feels like that thaumcraft causes error when trying to get block metadata. Could @Azanor help?

**Comment by Kiskae** [comment]
Looking at the stack trace, this appears to occur during the blockbreak event and appears to involve a block being set to air earlier than thaumcraft assumes it would be. 
Perhaps event order issue / sponge changing minecraft's internal data too soon?

**Comment by JBYoshi** [comment]
@Zidane I can't find a `callBlockBreakEvent` in `SpongeForgeEventFactory`... Which SpongeForge commit is this?

**Comment by Zidane** [comment]
@JBYoshi 

Thinking back on it, I think my local sources are messed up

**Comment by Zidane** [comment]
@JBYoshi 

https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/event/SpongeForgeEventFactory.java#L766

**Comment by JBYoshi** [comment]
@Zidane In your test condition, did it happen when placing a block or breaking a block? (I know it was placing/breaking since it involves an air block and a non-air block.)

**Comment by Zidane** [comment]
Break

**Comment by Zidane** [comment]
Got another one when breaking a dispenser while cancelling all change block events caused by me:

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:727) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:385) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:174) ~[BlockState$StateImplementation.class:?]
	at net.minecraft.block.BlockDispenser.getMetaFromState(BlockDispenser.java:275) ~[BlockDispenser.class:?]
	at net.minecraft.block.Block.getHarvestTool(Block.java:2218) ~[Block.class:?]
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:132) ~[ForgeHooks.class:?]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:82) ~[BlockEvent$BreakEvent.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockBreakEvent(SpongeForgeEventFactory.java:783) ~[SpongeForgeEventFactory.class:?]
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:309) ~[SpongeForgeEventFactory.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.postBulk(SpongeModEventManager.java:201) ~[SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) ~[SpongeModEventManager.class:?]
	at net.minecraft.world.World.handlePostTickCaptures(World.java:806) ~[World.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(PacketThreadUtil.java:60) ~[PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:24) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
```

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeForge/commit/eace33dc0a6195feebba7a3159dc7507cd8b436b
