### ISSUE TITLE
UserStorage Service not available during GameState#INITIALIZATION

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#291]
It throws this error if I try and use it.
<http://pastebin.com/F7CLiiyc>
This feels like a bug, but I'm not sure.

**Comment by gabizou** [comment]
Most services aren't completely finished loading by init. To be honest, the services should only really be considered ready for use by post init or load complete. Might be worth a few tests with the different phases and probably share your findings.

**Comment by gravityfox** [comment]
UserStorage feels a little strange being a service, considering that it's one of those things you might use for loading.

**Comment by gabizou** [comment]
@gravityfox It's likely going to no longer remain as a "service" from the same standpoint as other services, much like `SerializationManager` and such.

**Comment by ryantheleach** [comment]
I thought the original thinking behind having UserStorage as a service, was so you could swap it out for a plugin that provides a MySQL UserStorage implementation for example?

**Comment by simon816** [comment]
Remember that user storage gets its data from the world playerdata files, so that means the worlds would have to be loaded in order to know where to look. I think `SERVER_ABOUT_TO_START` or `SERVER_STARTING` would be the earliest time this data is available

**Comment by gravityfox** [comment]
So as it turns out `SERVER_ABOUT_TO_START` is still too early for it. Have a stack-trace.

```plain
[02:46:53] [Server thread/ERROR] [Sponge]: Could not pass FMLServerAboutToStartEvent to Plugin{id=foxguard, name=FoxGuard, version=0.14.3-SNAPSHOT}
java.lang.NullPointerException
	at org.spongepowered.common.service.user.UserDiscoverer.getPlayerDataFile(UserDiscoverer.java:220) ~[UserDiscoverer.class:?]
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:174) ~[UserDiscoverer.class:?]
	at org.spongepowered.common.service.user.UserDiscoverer.findByUuid(UserDiscoverer.java:87) ~[UserDiscoverer.class:?]
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:46) ~[SpongeUserStorageService.class:?]
	at net.foxdenstudio.sponge.foxguard.plugin.object.factory.FGHandlerFactory.createHandler(FGHandlerFactory.java:109) ~[FGHandlerFactory.class:?]
	at net.foxdenstudio.sponge.foxguard.plugin.object.factory.FGFactoryManager.createHandler(FGFactoryManager.java:93) ~[FGFactoryManager.class:?]
	at net.foxdenstudio.sponge.foxguard.plugin.FGStorageManager.loadHandlers(FGStorageManager.java:126) ~[FGStorageManager.class:?]
	at net.foxdenstudio.sponge.foxguard.plugin.FoxGuardMain.serverAboutToStart(FoxGuardMain.java:169) ~[FoxGuardMain.class:?]
	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_FoxGuardMain_serverAboutToStart5.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:233) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:277) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:166) [SpongeMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.onPost(LoadController.java:53) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:851) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:260) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:500) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by gabizou** [comment]
> So as it turns out SERVER_ABOUT_TO_START is still too early for it.

More than likely, yes, because the `GameAboutToStartServerEvent` is thrown before worlds start loading, which in this case, is before any of the world folders are actually known, thus returning null for the world folder to retrieve the Player's `GameProfile`.

**Comment by Zidane** [comment]
Closing this as the UserStorageService is reliant on Overworld being loaded which doesn't happen till after SERVER_ABOUT_TO_START.
