### ISSUE TITLE
PositionOutOfBoundsException when opening chest at (0, 0, 0)

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#355]
I told MC to open a chest at (0, 0, 0) with the following code (assumes there is such a chest):
```java
for (Player p : Sponge.getGame().getServer()
                        .getOnlinePlayers()) {
                    EntityPlayerMP mp = (EntityPlayerMP) p;
                    mp.displayGUIChest((IInventory) ((World) theWorld)
                            .getTileEntity(new BlockPos(0, 0, 0)));
                }
```
Lo and behold:
```
org.spongepowered.api.util.PositionOutOfBoundsException: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 255, 29999999) but got (0, -1, 0)
	at net.minecraft.world.World.checkBlockBounds(World.java:1937) ~[World.class:?]
	at net.minecraft.world.World.getBlock(World.java:1508) ~[World.class:?]
	at net.minecraft.world.World.createSnapshot(World.java:2063) ~[World.class:?]
	at net.minecraft.world.World.createSnapshot(World.java:118) ~[World.class:?]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callNotifyNeighborEvent(SpongeCommonEventFactory.java:494) ~[SpongeCommonEventFactory.class:1.8-1577-2.1-DEV-0]
	at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:1197) ~[World.class:?]
	at net.minecraft.tileentity.TileEntityChest.openInventory(TileEntityChest.java:453) ~[TileEntityChest.class:?]
	at net.minecraft.inventory.ContainerChest.<init>(ContainerChest.java:16) ~[ContainerChest.class:?]
	at net.minecraft.tileentity.TileEntityChest.createContainer(TileEntityChest.java:508) ~[TileEntityChest.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.displayGUIChest(EntityPlayerMP.java:809) ~[EntityPlayerMP.class:?]
 .... blah blah blah
```

**Comment by Zidane** [comment]
@kenzierocks 

This is the perils of using internals:

```
this.worldObj.notifyNeighborsOfStateChange(this.pos.down(), this.getBlockType());
```

In ```openContainer```
