### ISSUE TITLE
Error MatterProperty

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#367]
I try to check whether the solid block.
Code:
```
public static boolean BlockIsSolidMethod(Location location){
        String matterName = location.getBlock().getProperty(MatterProperty.class).get().getValue().name();
        return "SOLID".equals(matterName);
    }
```
Result:
```
[16:18:51] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'test' for source EntityPlayerMP['azat'/437, l='world', x=187,34, y=64,00, z=323,75]: Method net/minecraft/block/state/BlockState$StateImplementation.getProperty(Ljava/lang/Class;)Ljava/util/Optional; is abstract
java.lang.AbstractMethodError: Method net/minecraft/block/state/BlockState$StateImplementation.getProperty(Ljava/lang/Class;)Ljava/util/Optional; is abstract
	at net.minecraft.block.state.BlockState$StateImplementation.getProperty(BlockState.java) ~[beg.class:?]
	at io.github.azatik.grave.utils.BlockIsSolid.BlockIsSolidMethod(BlockIsSolid.java:8) ~[BlockIsSolid.class:?]
	at io.github.azatik.grave.commands.TestCmd.execute(TestCmd.java:50) ~[TestCmd.class:?]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:334) ~[CommandSpec.class:1.8-1577-2.1-DEV-967]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:334) ~[SimpleDispatcher.class:1.8-1577-2.1-DEV-967]
	at org.spongepowered.api.command.SimpleCommandManager.process(SimpleCommandManager.java:245) [SimpleCommandManager.class:1.8-1577-2.1-DEV-967]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) [rj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) [rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(SourceFile:85) [ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/7992e909bc85eb2c401966d47c7bcc3d09ff995f
