### ISSUE TITLE
InventoryTransactionResult IllegalStateException

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeCommon#384]
``` java
ItemStack record = ItemStack.builder().itemType(ItemTypes.RECORD_CAT).quantity(1).build();
Text name = Text.of("test");
record.offer(Keys.DISPLAY_NAME, name);
InventoryTransactionResult result = player.getInventory().offer(record);
```

will result in 
```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[guava-17.0.jar:?]
	at org.spongepowered.api.item.inventory.transaction.InventoryTransactionResult$Builder.build(InventoryTransactionResult.java:181) ~[InventoryTransactionResult$Builder.class:?]
	at org.spongepowered.common.item.inventory.adapter.impl.Adapter$Logic.appendSequential(Adapter.java:222) ~[Adapter$Logic.class:?]
	at org.spongepowered.common.item.inventory.adapter.impl.Adapter$Logic.appendSequential(Adapter.java:193) ~[Adapter$Logic.class:?]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.offer(MinecraftInventoryAdapter.java:72) ~[MinecraftInventoryAdapter.class:?]
```

It also seems to add the unnamed item into the inventory

**Comment by Mumfrey** [comment]
Ah I see what's happened. Before I rebased I didn't know that `InventoryOperationResult` had been replaced with `InventoryTransactionResult` in the API, so when I rebased I naturally replaced my concrete classes with the new one from the API, since the contract looked the same. However as you can see, before it was deleted [my OperationResult defaulted to SUCCESS](https://github.com/SpongePowered/SpongeCommon/blob/dd83fc734e837535903c1e2eda25808230ad4f42/src/main/java/org/spongepowered/common/item/inventory/struct/OperationResult.java#L45) and expects a failure state to be set only if necessary, however it seems the contract on [InventoryTransactionResult] is actually different and requires SUCCESS to be set explicitly.

The data in the itemstack is currently removed because I need to consult with @gabizou about cloning the data on item stacks. The item stacks are currently [defensively copied before insertion](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/item/inventory/util/ItemStackUtil.java#L60-L68) but this currently omits the metadata (hence the `TODO`s).

I will be generally tidying up Inventory anyway and these issues are both easily fixed.

**Comment by clienthax** [comment]
@Mumfrey Thankya <3

**Comment by Mumfrey** [comment]
@clienthax can you check this works for your use, it works in my tests now.
