### ISSUE TITLE
Enabling world configuration for main world crashes server

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#404]
@Zidane 

If I enable the world configuration generated by Sponge for the main worlds and enable it it will always crash the server on start, no matter what I set in the configuration. This is happening because it always resets my changes and the defaults for the configuration file are generally wrong for the main worlds (all options set to false even though main world should always load-on-startup be enabled etc...).

```
[18:46:07] [Server thread/INFO]: Preparing level "world"
[18:46:07] [Server thread/INFO] [Sponge]: Checking for worlds that need to be migrated...
[18:46:08] [Server thread/WARN] [Sponge]: World [world] (DIM0) is set to not load on startup. To load it later, enable [load-on-startup] in config or use a plugin
[18:46:08] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@79ba68b0)
[18:46:08] [Server thread/INFO] [FML]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@79ba68b0)
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 1/6/16 6:46 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.server.management.ServerConfigurationManager.setPlayerManager(ServerConfigurationManager.java:477)
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:449)
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:262)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:500)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 4.3.3-2-ARCH
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1116773048 bytes (1065 MB) / 1665138688 bytes (1588 MB) up to 7462191104 bytes (7116 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.4.1577-PROJECT(SpongeForge).jar) 
	UCHIJAA	Forge{11.14.4.1577} [Minecraft Forge] (forgeSrc-1.8-11.14.4.1577-PROJECT(SpongeForge).jar) 
	UCHIJAA	sponge{$version} [SpongeForge] (SpongeForge) 
	UCHIJAA	nostalgiagen{0.2-SNAPSHOT} [NostalgiaGen] (nostalgiagen-0.3-SNAPSHOT.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (unknown)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by simon816** [comment]
> [18:46:08] [Server thread/WARN] [Sponge]: World [world] (DIM0) is set to not load on startup. To load it later, enable [load-on-startup] in config or use a plugin

It should not be possible to disable the overworld, that's where the problem lies

**Comment by Minecrell** [comment]
The point is Sponge is disabling the world, not me. If I keep it enabled it will replace that again once the server is started.
