### ISSUE TITLE
Modified inventory crashes server

### ISSUE THREAD

**Issue by JonathanxD** [SpongePowered/SpongeCommon#409]
If client has a mod that modifies inventory size (like OverpoweredInventory) when he click on any slot the server will crashes
Crash Report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8-1577-3.1.0-BETA-1025.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 08/01/16 14:20
Description: Exception ticking world

java.lang.IndexOutOfBoundsException: Index: 171, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:114)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:310)
	at net.minecraft.world.World.handlePostTickCaptures(World.java:965)
	at net.minecraft.world.SpawnerAnimals.onFindChunksForSpawningReturn(SpawnerAnimals.java:85)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:200)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:199)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:114)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:310)
	at net.minecraft.world.World.handlePostTickCaptures(World.java:965)
	at net.minecraft.world.SpawnerAnimals.onFindChunksForSpawningReturn(SpawnerAnimals.java:85)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:200)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:199)

-- Affected level --
Details:
	Level name: DIM1
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 5543792134060270998
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 0,00,50,00,0,00 - World: (0,50,0), Chunk: (at 0,3,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4781 game time, 4781 day time
	Level dimension: 1
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:693)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 4.3.3-2-ARCH
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 185158400 bytes (176 MB) / 490733568 bytes (468 MB) up to 855638016 bytes (816 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577-universal.jar) 
	UCHIJAAAA	Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577-universal.jar) 
	UCHIJAAAA	sponge{1.8-1577-3.1.0-BETA-1025} [SpongeForge] (spongeforge-1.8-1577-3.1.0-BETA-1025.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8-1577-3.1.0-BETA-1025.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['TheRealBuggy'/1299, l='world', x=-32,56, y=91,00, z=150,04]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)
```

Sorry my bad english.

**Comment by JonathanxD** [comment]
Bump. Any solution?

**Comment by modwizcode** [comment]
Hey @Mumfrey would mind if I took this one? I think I could get it done pretty quick.

**Comment by Mumfrey** [comment]
Go ahead. Personally I feel like invalid packets from the client should be grounds to kick the client.

**Comment by modwizcode** [comment]
I didn't think this was a packet related issue but I haven't loaded it up
to reproduce it yet. I was starting with the assumption that sponge has a
problem with custom sizes that isn't handled properly.

**Comment by Mumfrey** [comment]
I was starting with the assumption that this is a poorly-written mod which doesn't realise its server-side counterpart is missing and sends click packets for slots which don't exist. I could be wrong but that's where I would start.

**Comment by Mumfrey** [comment]
FYI, you can tell the server-side version of the mod isn't installed because the crash log lists only fml, mcp, forge and sponge. This isn't a case of a server-side mod breaking sponge, this is a case of a client-side mod which isn't smart enough to disable itself.

**Comment by modwizcode** [comment]
Ah ok cool that should be an easy fix then.

**Comment by modwizcode** [comment]
Hmm, I can't reproduce this with current SpongeForge and current overpowered inventories. The extra inventory tab just doesn't work in the latest version.

**Comment by Zidane** [comment]
Pretty sure @Grinch fixed this with his last two PRs.
