### ISSUE TITLE
TextXML can't survive a roundtrip.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#437]
```
xml = TextSerializers.TEXT_XML.serialize(message);
p.sendMessage(ChatTypes.CHAT, TextSerializers.TEXT_XML.deserialize(xml)));
```
results in an exception being thrown. the xml deserializer can't handle the encoded <> symbols that it outputs as a valid onclick listener.

```
[08:31:22] [pool-2-thread-1/ERROR] [TranslateWithBing]: threw an exception while parsing xml
org.spongepowered.api.text.serializer.TextParseException: Error parsing TextXML message
	at org.spongepowered.common.text.serializer.xml.TextXmlTextSerializer.deserialize(TextXmlTextSerializer.java:95) ~[TextXmlTextSerializer.class:?]
	at au.id.rleach.translate.TranslateWithBing.lambda$null$3(TranslateWithBing.java:98) ~[TranslateWithBing.class:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_66]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_66]
	at au.id.rleach.translate.TranslateWithBing.lambda$null$4(TranslateWithBing.java:98) ~[TranslateWithBing.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_66]
	at au.id.rleach.translate.TranslateWithBing.lambda$sendTranslatedMessages$5(TranslateWithBing.java:88) ~[TranslateWithBing.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$9(Task.java:138) ~[Task$Builder.class:?]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$2(SchedulerBase.java:177) ~[SchedulerBase.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: Invalid click handler
	at org.spongepowered.common.text.serializer.xml.Element.applyTextActions(Element.java:108) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:163) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Tr.toText(Tr.java:55) ~[Tr.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:149) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.builderFromObject(Element.java:172) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.Element.toText(Element.java:149) ~[Element.class:?]
	at org.spongepowered.common.text.serializer.xml.TextXmlTextSerializer.deserialize(TextXmlTextSerializer.java:93) ~[TextXmlTextSerializer.class:?]
	... 14 more
[08:31:22] [pool-2-thread-1/ERROR] [TranslateWithBing]: 

```

```
<span><tr key="chat.type.text"><span onClick="suggest_command('/msg Player385 ')" onShiftClick="insert_text('Player385)" onHover="show_entity('&lt;span&gt;{name:&quot;Player385&quot;,id:&quot;1e3c9076-6029-36c6-8475-dd38d2030d5f&quot;}&lt;/span&gt;')"><span>Player385</span></span><span>test</span></tr></span>
```

**Comment by ryantheleach** [comment]
@zml2008 @TomyLobo

**Comment by TomyLobo** [comment]
Hmm, this should not have happened. Looks like someone isn't using a proper serializer for this, that's all I can say.

**Comment by ryantheleach** [comment]
If the onShiftClick lacks a single quote, it's because the generator only generated a single quote.

**Comment by TomyLobo** [comment]
There, I fixed it.
