### ISSUE TITLE
Placing a decorated banner = Fatal error, FutureTask - optional get()

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#45]
Upgraded to sponge dev 456 to confirm:

Solid color banners can be placed about just fine.  Dye a banner, place it, and the banner does not appear, inventory is decreased to a red 0 in client (which can also go negative as placed more times).  Block-update the area with a regular block or solid banner, and all the placed banners (including the ones below 0) appear in client.  Other clients will see such blocks appear if they logout and log back in.

The server throws the following error when a dyed banner is placed, but not for solid colored banners:
[code]
```

[20:00:38] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.7.0_71]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.7.0_71]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:710) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
        at com.google.common.base.Absent.get(Absent.java:47) ~[minecraft_server.1.8.jar:?]
        at net.minecraft.tileentity.TileEntityBanner.updatePatterns(SourceFile:87) ~[bci.class:?]
        at net.minecraft.tileentity.TileEntityBanner.onSetItemValues(SourceFile:65) ~[bci.class:?]
        at net.minecraft.tileentity.TileEntityBanner.func_175112_a(SourceFile:284) ~[bci.class:?]
        at net.minecraft.item.ItemBanner.func_180614_a(SourceFile:66) ~[ajs.class:?]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:568) ~[ForgeHooks.class:?]
        at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:132) ~[amj.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:446) ~[qx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:595) ~[rj.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_180769_a(SourceFile:59) ~[mx.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[mx.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.7.0_71]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.7.0_71]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:709) ~[FMLCommonHandler.class:?]
        ... 5 more
[/code]

... 

Have tested only with a few dyed patterns, not exhaustively tested all types of banners, figured the error code would imply a general issue :)

**Comment by theboomer** [comment]
Also, this was tested with JUST forge, and does not occur - it is a sponge thing

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/e2073473d7b606d729be568e7260a33a3e74d6a5
