### ISSUE TITLE
Cancelling inv events cast issue

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeCommon#450]
Cancelling ClickInventoryEvent

```
[18:39:16] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter cannot be cast to net.minecraft.inventory.Slot
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_66]
	at net.minecraft.util.Util.runTask(Util.java:23) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:736) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.ClassCastException: org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter cannot be cast to net.minecraft.inventory.Slot
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:441) ~[SpongeCommonEventFactory.class:?]
	at net.minecraft.world.World.handlePostTickCaptures(World.java:968) ~[World.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:108) ~[PacketUtil.class:?]
	at net.minecraft.network.PacketThreadUtil$1.onProcessPacket(PacketThreadUtil.java:51) ~[PacketThreadUtil$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_66]
	at net.minecraft.util.Util.runTask(Util.java:22) ~[Util.class:?]
	... 5 more
```

Also invalidating each transaction seems to have no effect

**Comment by Zidane** [comment]
@bloodmc 

Status update. Didn't you make changes to inventory events?

**Comment by Mumfrey** [comment]
@clienthax does this still happen, I'm looking at the code and can't see what would be throwing this?

**Comment by kashike** [comment]
I believe this was fixed with https://github.com/SpongePowered/SpongeCommon/commit/7bd6066ffda1ef719abe1ac584058b5383ab946e.

**Comment by Zidane** [comment]
Closing this until @clienthax says otherwise.
