### ISSUE TITLE
NPE when giving potion effects to a new Potion Entity

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#456]
````java
java.lang.NullPointerException
        at org.spongepowered.common.data.processor.data.entity.PotionEntityPotionDataProcessor.getVal(PotionEntityPotionDataProcessor.java:69) ~[PotionEntityPotionDataProcessor.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.data.processor.data.entity.PotionEntityPotionDataProcessor.getVal(PotionEntityPotionDataProcessor.java:50) ~[PotionEntityPotionDataProcessor.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.data.processor.common.AbstractSingleDataSingleTargetProcessor.offerToStore(AbstractSingleDataSingleTargetProcessor.java:183) ~[AbstractSingleDataSingleTargetProcessor.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.data.util.ValueProcessorDelegate.offerToStore(ValueProcessorDelegate.java:106) ~[ValueProcessorDelegate.class:1.8.9-1722-3.1.0-BETA-1104]
        at net.minecraft.entity.Entity.offer(Entity.java:122) ~[pk.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.runAttack(ShnugglesPrimeInstance.java:467) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.runRandomAttack(ShnugglesPrimeInstance.java:265) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.run(ShnugglesPrimeInstance.java:128) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeManager.run(ShnugglesPrimeManager.java:197) ~[ShnugglesPrimeManager.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$9(Task.java:138) ~[Task$Builder.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$63(SchedulerBase.java:177) ~[SchedulerBase.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.8.9-1722-3.1.0-BETA-1104]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_65]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:186) [SpongeScheduler.class:1.8.9-1722-3.1.0-BETA-1104]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:222) [SpongeMod.class:1.8.9-1722-3.1.0-BETA-1104]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:82) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:59) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:265) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:594) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
````

````java
PotionEffect instantDamageEffect = PotionEffect.of(PotionEffectTypes.INSTANT_DAMAGE, 0, 1);

World w = ...;
Location<World targetLoc = ...;

Optional<Entity> optEntity = w.createEntity(
        EntityTypes.SPLASH_POTION,
        targetLoc.getPosition()
);

if (optEntity.isPresent()) {
    Entity potion = optEntity.get();
    potion.offer(Keys.POTION_EFFECTS, Lists.newArrayList(instantDamageEffect));
    w.spawnEntity(entity, Cause.of(this));
}
````

**Comment by Zidane** [comment]
@gabizou 

Status update.

**Comment by gabizou** [comment]
I'll work on it after I get these mixins working again.
