### ISSUE TITLE
SqlService cannot be used

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#459]
Attempting to use the `SqlService` provided by `SpongeCommon`, specifically concerning `H2`, is not possible as it currently stands. The plugin available [here](https://github.com/kenzierocks/NoSqlService) (check releases for binaries, or use `gradle runServer`) will give something like the output [here](https://gist.github.com/kenzierocks/1b5bffaa39b072d73d8e). This should be patched, as `H2` is the recommended SQL implementation.

**Comment by Minecrell** [comment]
The sql service is working fine, although I think your plugin is broken:

```
org.h2.jdbc.JdbcSQLException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:config/nosql/test.h2". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-191]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[DbException.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.message.DbException.get(DbException.java:179) ~[DbException.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.message.DbException.get(DbException.java:155) ~[DbException.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:400) ~[ConnectionInfo.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.Engine.openSession(Engine.java:50) ~[Engine.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.Engine.openSession(Engine.java:175) ~[Engine.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153) ~[Engine.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.Engine.createSession(Engine.java:136) ~[Engine.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[Engine.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349) ~[SessionRemote.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107) ~[JdbcConnection.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91) ~[JdbcConnection.class:1.8.9-1722-3.1.0-BETA-1114]
	at org.h2.Driver.connect(Driver.java:72) ~[Driver.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[DriverDataSource.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314) ~[PoolBase.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171) ~[PoolBase.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436) [HikariPool.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65) [HikariPool.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567) [HikariPool$PoolEntryCreator.class:1.8.9-1722-3.1.0-BETA-1114]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560) [HikariPool$PoolEntryCreator.class:1.8.9-1722-3.1.0-BETA-1114]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

The problem you're facing here is neither a SpongeCommon bug nor an actual SpongeForge bug, it is related to changes [Forge made recently for the Eclipse dev environment](https://github.com/MinecraftForge/MinecraftForge/commit/f3c2eb8e9cda873678d0e2308e4b7904fe8e3d61#diff-01042e0e40a00cc58f70263a1aaf84e7R29) probably to fix some issues with the Eclipse compiler. As you can see in the commit, the issue is in Forge, because the class that is failing to load is from a [clearly marked optional dependency of HikariCP](https://github.com/brettwooldridge/HikariCP/blob/master/pom.xml#L122-L128). The sql service is working fine with your plugin in SpongeVanilla, SpongeForge in IntelliJ IDEA as well as in production (except that it fails to open the connection to the database). 

You have different options to solve this problem:
- Add the dependency manually to your development environment.
- [Downgrade ForgeGradle to a version which doesn't have this option in Forge enabled]() or simply remove `-DFORGE_FORCE_FRAME_RECALC=true` from the VM options in your run configuration. This may break other things, I don't know.
- Report this problem to Forge, as you can see in the comment I've linked above this is a kind of expected problem which just didn't happen yet in Forge itself or any mod.
- Use an IDE without a broken compiler.

**Comment by kenzierocks** [comment]
1) No, I want setup to be easy.
2) Don't think that's possible, especially if we switch to 1.9 later
3) Might do that
4) No, I have big reasons for using Eclipse.

**Comment by Minecrell** [comment]
Well in that case 3) is probably the best option for you.

**Comment by kenzierocks** [comment]
Looks like disabling the launch flag is going to be my current option. I don't know what bug that flag fixes, but I haven't hit it.
