### ISSUE TITLE
Restoring BlockSnapshots Rapidly With Timings Causes CME

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#478]
``` java
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_65]
        at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_65]
        at co.aikar.util.JSONUtil.mapArray(JSONUtil.java:93) ~[JSONUtil.class:1.8.9-1722-3.1.0-BETA-0]
        at co.aikar.timings.TimingHistory.lambda$new$6(TimingHistory.java:100) ~[TimingHistory.class:1.8.9-1722-3.1.0-BETA-0]
        at co.aikar.util.JSONUtil.mapArrayToObject(JSONUtil.java:109) ~[JSONUtil.class:1.8.9-1722-3.1.0-BETA-0]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:99) ~[TimingHistory.class:1.8.9-1722-3.1.0-BETA-0]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:101) ~[FullServerTickHandler.class:1.8.9-1722-3.1.0-BETA-0]
        at net.minecraft.server.MinecraftServer.onTickEnd(MinecraftServer.java:44) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:650) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
```

**Comment by bloodmc** [comment]
uh did you have timings on? Timings should not be showing up in any traces unless you turn it on manually.

**Comment by DarkArc** [comment]
They're on, though I didn't manually enable them.

**Comment by Minecrell** [comment]
Still, ensbling timing should cause the server to crash ;)

**Comment by simon816** [comment]
How are you restoring blocks? All in the main thread (same tick) ?

**Comment by DarkArc** [comment]
@simon816 Yes. 

https://github.com/sk89q/WorldEdit/blob/feature/sponge-new/worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongeWorld.java#L113-L119
https://github.com/sk89q/WorldEdit/blob/feature/sponge-new/worldedit-sponge/src/main/java/com/sk89q/worldedit/sponge/SpongeForgeWorld.java#L85-L104

**Comment by bloodmc** [comment]
Just turn timings off and you won't have a problem. Update ticket to reflect timing bug when restoring.

**Comment by gabizou** [comment]
Can you verify this is still an issue? Granted, this is very old now, and long before CauseTracker was rewritten (though it might suffer from the same issue).

**Comment by DarkArc** [comment]
I'm not currently setup for MC dev. I will go ahead and close this.. After I get my new computer built, I'll set something up and try that out. Should be about a week or a little over.
