### ISSUE TITLE
Exception on retrieving JoinData on player first join

### ISSUE THREAD

**Issue by jk-5** [SpongePowered/SpongeCommon#511]
#### Example Code

    @Listener
    public void onJoin(ClientConnectionEvent.Login event){
        Optional<JoinData> joinData = event.getTargetUser().get(JoinData.class); // <-- Exception
        if(joinData.isPresent()){
            // Do stuff
        }
    }

#### Expected behavior
The JoinData for the user does not exist yet, so Optional.empty() is returned.

#### Exception
    java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_72]
        at org.spongepowered.common.data.processor.multi.entity.JoinDataProcessor.getValues(JoinDataProcessor.java:68) ~[JoinDataProcessor.class:?]
        at org.spongepowered.common.data.processor.multi.entity.JoinDataProcessor.getValues(JoinDataProcessor.java:45) ~[JoinDataProcessor.class:?]
        at org.spongepowered.common.data.processor.common.AbstractMultiDataSingleTargetProcessor.from(AbstractMultiDataSingleTargetProcessor.java:76) ~[AbstractMultiDataSingleTargetProcessor.class:?]
        at org.spongepowered.common.data.util.DataProcessorDelegate.from(DataProcessorDelegate.java:94) ~[DataProcessorDelegate.class:?]
        at net.minecraft.entity.Entity.get(Entity.java:62) ~[Entity.class:?]
        at nl.jk5.pumpkin.server.map.MapEventListener.onJoin(MapEventListener.java:22) ~[MapEventListener.class:?]
        at org.spongepowered.common.event.listener.LoginListener_MapEventListener_onJoin7.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:?]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:236) [SpongeModEventManager.class:?]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:280) [SpongeModEventManager.class:?]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:248) [SpongeModEventManager.class:?]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:127) [SpongeImpl.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:206) [ServerConfigurationManager.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:242) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:142) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:65) [FMLNetworkHandler.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137) [NetHandlerLoginServer.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64) [NetHandlerLoginServer.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:310) [NetworkManager.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:204) [NetworkSystem.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:800) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:365) [DedicatedServer.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]

**Comment by gabizou** [comment]
You can't get user data in login. You have to get it through `ClientConnectEvent.Join`.

**Comment by gabizou** [comment]
But this overall is just an issue where `User` doesn't fully implement `DataHolder` whatsoever, which is a separate related issue altogether.

**Comment by jk-5** [comment]
I do query it from ClientConnectionEvent.Login. See the example code

Ok that makes sense, i'll see what i can do to add the DataHolder implementation / temporarily work around it
