### ISSUE TITLE
IndexOutOfBoundsException: Index: 55, Size: 45

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#550]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1762-3.1.0-BETA-1167.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 2/28/16 4:53 AM
Description: Exception ticking world

java.lang.IndexOutOfBoundsException: Index: 55, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:273)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:493)
	at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1028)
	at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:110)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:273)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:493)
	at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1028)
	at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:110)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)

-- Affected level --
Details:
	Level name: ResourceWorld
	All players: 1 total; [EntityPlayerMP['XxXCrazyCatXxX'/19674768, l='ResourceWorld', x=-4.30, y=78.00, z=-4718.47]]
	Chunk stats: ServerChunkCache: 861 Drop: 0
	Level seed: 1616924059552065417
	Level generator: ID 09 - overworld, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: 140.00,64.00,252.00 - World: (140,64,252), Chunk: (at 12,4,12 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 70153121 game time, 48897081 day time
	Level dimension: 2
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-431.23.3.el6.x86_64
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 657168368 bytes (626 MB) / 6291980288 bytes (6000 MB) up to 7477395456 bytes (7131 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1762 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762-universal.jar) 
	UCHIJAAAA	sponge{1.8.9-1762-3.1.0-BETA-1167} [SpongeForge] (spongeforge-1.8.9-1762-3.1.0-BETA-1167.jar) 
	UCHIJAAAA	CommandLogger{1.0} [CommandLogger] (CommandLogger.jar) 
	UCHIJAAAA	Darmok{2.0} [Darmok] (Darmok-v1.0-30-gfec3116.jar) 
	UCHIJAAAA	dhmcstats{2.0} [dhmcstats] (dhmcstats.jar) 
	UCHIJAAAA	EssentialCmds{7.5-754e323} [EssentialCmds] (EssentialCmds-7.5.jar) 
	UCHIJAAAA	Keys{1.0} [Keys] (Keys-1.0.1.jar) 
	UCHIJAAAA	Oracle{2.0} [Oracle] (Oracle.jar) 
	UCHIJAAAA	OreAlerts{1.0} [OreAlerts] (OreAlerts-1.1.jar) 
	UCHIJAAAA	PermissionsEx{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	Prism{3.0} [Prism] (Prism-3.0.0-beta1-14-g976a60f-all.jar) 
	UCHIJAAAA	SafeGuard{1.0} [SafeGuard] (SafeGuard-1.0.0-dev-16-gb17f4e3.jar) 
	UCHIJAAAA	Vanish{4.0.0} [Vanish] (vanish-4.0.0.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1762-3.1.0-BETA-1167.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 3 / 500; [EntityPlayerMP['weels1566'/19547203, l='world', x=-3550.52, y=20.00, z=3176.58], EntityPlayerMP['Blazenery'/19584649, l='world', x=4713.41, y=30.60, z=-930.94], EntityPlayerMP['XxXCrazyCatXxX'/19674768, l='ResourceWorld', x=-4.30, y=78.00, z=-4718.47]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,SpongeForge'
	Type: Dedicated Server (map_server.txt)

**Comment by gabizou** [comment]
Closing as I believe @Grinch fixed this a few days ago.
