### ISSUE TITLE
GameProfileManager.getAllByName() produces ConcurrentModificationException

### ISSUE THREAD

**Issue by minecrafter** [SpongePowered/SpongeCommon#567]
```
[07:46:00] [pool-2-thread-1/ERROR] [buycraft]: Unable to fetch player profiles
java.util.ConcurrentModificationException
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1545) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74]
	at org.spongepowered.common.profile.query.Query.fromNames(Query.java:115) ~[Query.class:1.8.9-1763-4.0.1-BETA-1184]
	at org.spongepowered.common.profile.query.NameQuery$MultiGet.call(NameQuery.java:72) ~[NameQuery$MultiGet.class:1.8.9-1763-4.0.1-BETA-1184]
	at org.spongepowered.common.profile.query.NameQuery$MultiGet.call(NameQuery.java:57) ~[NameQuery$MultiGet.class:1.8.9-1763-4.0.1-BETA-1184]
	at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$32(Functional.java:127) ~[Functional.class:1.8.9-1763-4.0.1-BETA-1184]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_74]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_74]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
```

The code that causes this is rather straightforward:

```java
        usernames.add("MHF_Question");
        CompletableFuture<Collection<GameProfile>> future = Sponge.getServer().getGameProfileManager().getAllByName(usernames, true);
        future.whenComplete((result, throwable) -> {
            if (throwable != null) {
                plugin.getLogger().error("Unable to fetch player profiles", throwable);
                return;
            }

            Map<String, GameProfile> profileMap = result.stream().filter(p -> p.getName().isPresent())
                    .collect(Collectors.toMap(p -> p.getName().get(), Function.identity()));

            Sponge.getScheduler().createTaskBuilder()
                    .execute(new SignUpdateApplication(plugin, signToPurchases, profileMap))
                    .submit(plugin);
        });
```

**Comment by minecrafter** [comment]
Sponge version:
```
> sponge version
[07:51:51] [Server thread/INFO]: SpongeForge
    Minecraft: 1.8.9
    SpongeAPI: 4.0.1-ac3f07d
    SpongeForge: 1.8.9-1763-4.0.1-BETA-1184
    Minecraft Forge: 11.15.1.1764
```

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/a558930c5543479d2dddbee94e12cfd43af59028.
