### ISSUE TITLE
Asset loading is broken on Windows

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#570]
The asset manager is currently not usable on Windows due to different path separators returned by the `Path` implementation on Windows (it returns the platform-native path separators). Because of that the implementation will not find the resource because the `URL` to the resource is constructed with the platform-specific `Path` String representation.

A temporary fix would be replacing the Windows path separators with normal slashes, however the asset manager should likely not use `Path` at all, and rather just operate on a String because `Path`'s behaviour is always specific to the behaviour of the underlying file system.

Test plugin:

```java
@Plugin(id = "net.minecrell.testplugin")
public final class TestPlugin {

    @Inject
    private Logger logger;

    @Inject
    private AssetManager assets;

    @Listener
    public void onPreInit(GamePreInitializationEvent event) throws IOException {
        Asset asset = this.assets.getAsset(this, "test.txt").get();
        this.logger.info(asset.readString());
    }

}
```

Working on Linux, on Windows it results in an error:

```
[19:38:43] [Server thread/ERROR] [Sponge]: Could not pass GamePreInitializationEvent$Impl to Plugin{id=net.minecrell.testplugin, name=testplugin, version=1.0-SNAPSHOT, source=mods\testplugin-1.0-SNAPSHOT.jar}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_74]
	at net.minecrell.testplugin.TestPlugin.onPreInit(TestPlugin.java:24) ~[TestPlugin.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_TestPlugin_onPreInit2.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-4.1.0-BETA-261]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:258) [SpongeEventManager.class:1.8.9-4.1.0-BETA-261]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:269) [SpongeEventManager.class:1.8.9-4.1.0-BETA-261]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:273) [SpongeEventManager.class:1.8.9-4.1.0-BETA-261]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:186) [SpongeImpl.class:1.8.9-4.1.0-BETA-261]
	at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:138) [SpongeVanilla.class:1.8.9-4.1.0-BETA-261]
	at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$0(SourceFile:60) [ko.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:98) [ko.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:421) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by windy1** [comment]
This could probably be fixed with 

```java
path.toString().replace(File.seperator, '/')
```

No? (I don't have a Windows env to test on)

**Comment by Minecrell** [comment]
Probably. I think you should only construct a Pah object when necessary as these will be always file system specific and therefore only used when actually interacting with the file system. For now it's fine but I'd replace it for later
