### ISSUE TITLE
WorldGen causes server crash

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#601]
```
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.NullPointerException
        at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:220) ~[aqq.class:?]
        at net.minecraft.world.gen.structure.MapGenStructure.func_175795_b(MapGenStructure.java:98) ~[aqq.class:?]
        at net.minecraft.world.gen.ChunkProviderHell.func_177458_a(ChunkProviderHell.java:470) ~[anw.class:?]
        at org.spongepowered.common.world.gen.SpongeChunkProvider.func_177458_a(SpongeChunkProvider.java:328) ~[SpongeChunkProvider.class:1.8.9-1763-4.1.0-BETA-0]
        at net.minecraft.world.gen.ChunkProviderServer.func_177458_a(ChunkProviderServer.java:376) ~[ld.class:?]
        at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:239) ~[le.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:114) ~[adt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:199) ~[le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by Minecrell** [comment]
Caused by https://github.com/SpongePowered/SpongeCommon/commit/fce3f106f722bc2a695e769befc8c0d51529efa9 although I have no idea why that error is happening
