### ISSUE TITLE
Click Interact Inventory Event triggers IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#602]
```
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_71]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_71]
        at net.minecraft.inventory.Container.func_75139_a(Container.java:111) ~[xi.class:?]
        at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:306) ~[SpongeCommonEventFactory.class:1.8.9-1763-4.1.0-BETA-0]
        at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:496) ~[CauseTracker.class:1.8.9-1763-4.1.0-BETA-0]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:108) ~[PacketUtil.class:1.8.9-1763-4.1.0-BETA-0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:51) ~[fh$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
```

**Comment by modwizcode** [comment]
What container? Are any mods installed? I thought this issue was resolved.

**Comment by DarkArc** [comment]
I don't know, appeared in my log.

**Comment by modwizcode** [comment]
Mods and or plugins installed?

**Comment by DarkArc** [comment]
WorldEdit, PermissionsEx, and a couple I wrote that you've probably never heard of. Regardless, nice of them are going to be sending invalid packets, which appears to be what the issue is here.

**Comment by modwizcode** [comment]
Client mods are usually the problem. I will investigate further when I get
home this issue was recently seen and addressed I assume it was inadequate
or this is a similar one.

**Comment by DarkArc** [comment]
This is probably just a case where we need to assume the packet should be ignored if it's outside of the parameters of what we expect.

**Comment by modwizcode** [comment]
Yeah but it could he a calculation error somewhere. Give me time to get
home from school and look.

**Comment by modwizcode** [comment]
No calculation error that I can see. The `MixinContainer` is just assuming all passed in data is valid. I can fix this in like 5 hours or someone else can address it.

**Comment by viveleroi** [comment]
We get a similar issue, which I assume is the exact same one, but it crashes us roughly once a day:

```
java.lang.IndexOutOfBoundsException: Index: 88, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:273)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:493)
	at net.minecraft.world.World.redirect$onUpdateTileEntities$0(World.java:281)
	at net.minecraft.world.World.func_72939_s(World.java:1718)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


java.lang.IndexOutOfBoundsException: Index: 58, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:111)
	at org.spongepowered.common.event.SpongeCommonEventFactory.handleClickInteractInventoryEvent(SpongeCommonEventFactory.java:273)
	at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:493)
	at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1028)
	at net.minecraft.world.WorldServer.redirect$onUpdateBlocks$0(WorldServer.java:110)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:431)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

etc..
