### ISSUE TITLE
minecraft.util.ReportedException: Exception while updating neighbours at CauseTracker.notifyBlockOfStateChange Caused by: java.util.NoSuchElementException: No value present at java.util.Optional.get()

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/SpongeCommon#607]
I've hit the exception below in https://github.com/vorburger/SwissKnightMinecraft/blob/633baf583981829c2ddd25a00c686fffa3191893/SpongePowered/MyFirstSpongePlugIn/src/main/java/ch/vorburger/minecraft/logo/UndoableTurtle.xtend

In https://github.com/SpongePowered/SpongeCommon/blob/0b269ba28274632f46a81f340fb4702dba4786a1/src/main/java/org/spongepowered/common/event/CauseTracker.java#L1105 I can see that the assumption seems to be that hasTickingBlock() => getCurrentTickBlock().isPresent(), but it looks like that's not (always?) the case? Perhaps it would be safer if that was written like this instead:

                        if (this.getCurrentTickBlock().isPresent()) {
                            source = this.getCurrentTickBlock().get();
                            sourcePos = VecHelper.toBlockPos(this.getCurrentTickBlock().get().getPosition());

looking further into the code, it appears that hasTickingBlock() is this.currentTickBlock != null and getCurrentTickBlock() is Optional.ofNullable(this.currentTickBlock), and actually the API should be simplified then, why have is* and Optional? Anyway, based on that this should never happen? But it does, for me. Or is there some Mixin magic happening here?

Or could this be some multi-threading issue?? Perhaps it would be safer if that was written like this instead:
                        if (this.hasTickingBlock()) {
                            source = this.getCurrentTickBlock().get();
                            sourcePos = VecHelper.toBlockPos(source.getPosition());

although that still isn't really fully multi thread safe, of course... if this could be multi thread related, then best would be something using ifPresent(Consumer<? super T> consumer) ?

*OR* could this by _MY FAULT_ - is it imaginable this error could be caused by a Plugin doing something like World.setBlockState() from any other thread than the "Server thread" ? If so, what's the appropriate API in Sponge to "submit something to be done on the 'Server thread' whenever it can next" - you know like SWT's Display asyncE‌xec (or similar mechanism in other UI frameworks such as Swing and JavaFX) - do you know what I mean? And if so, why doesn't Sponge have an autoamted "invalid thread access exception", again inspired by e.g. https://wiki.eclipse.org/FAQ_Why_do_I_get_an_invalid_thread_access_exception%3F

Let me know if a PR with any of the changes suggested above would be welcome.

```
[21:02:58] [ch.vorburger.hotea.watchdir.QuietPeriodListener/WARN] Could not undo Block, due to Minecraft Exception, for Block: SpongeBlockSnapshot{worldUniqueId=7ab50cdf-ab35-4091-b5a7-e72be980801a, position=(-4, 68, 186), blockState=minecraft:air, extendedState=minecraft:air}
net.minecraft.util.ReportedException: Exception while updating neighbours
	at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1140) ~[CauseTracker.class:?]
	at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:337) ~[World.class:?]
	at net.minecraft.world.World.notifyNeighborsRespectDebug(World.java:416) ~[World.class:?]
	at net.minecraft.world.World.markAndNotifyNeighbors(World.java:217) ~[World.class:?]
	at net.minecraft.world.World.setBlockState(World.java:185) ~[World.class:?]
	at org.spongepowered.common.block.SpongeBlockSnapshot.restore(SpongeBlockSnapshot.java:182) ~[SpongeBlockSnapshot.class:?]
	at ch.vorburger.minecraft.logo.UndoableTurtle.undo(UndoableTurtle.java:42) [bin/:?]
	at ch.vorburger.minecraft.logo.AbstractDrawingPlugin.onServerStopping(AbstractDrawingPlugin.java:46) [bin/:?]
	at ch.vorburger.minecraft.command.AbstractPluginWithCommands.onServerStopping(AbstractPluginWithCommands.java:37) [bin/:?]
	at org.spongepowered.common.event.listener.GameStoppingServerEventListener_AbstractPluginWithCommands_onServerStopping5.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) [RegisteredListener.class:?]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:269) [SpongeEventManager.class:?]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:297) [SpongeEventManager.class:?]
	at org.spongepowered.server.plugin.VanillaPluginManager.post(VanillaPluginManager.java:242) [VanillaPluginManager.class:?]
	at org.spongepowered.server.plugin.VanillaPluginManager.unloadPlugins(VanillaPluginManager.java:233) [VanillaPluginManager.class:?]
	at ch.vorburger.hotea.minecraft.HoteaListener.unload(HoteaListener.java:26) [HoteaListener.class:?]
	at ch.vorburger.hotea.minecraft.HoteaListener.onReload(HoteaListener.java:20) [HoteaListener.class:?]
	at ch.vorburger.hotea.HotClassLoaderImpl.notifyListeners(HotClassLoaderImpl.java:79) [HotClassLoaderImpl.class:?]
	at ch.vorburger.hotea.HotClassLoaderImpl.lambda$0(HotClassLoaderImpl.java:93) [HotClassLoaderImpl.class:?]
	at ch.vorburger.hotea.HotClassLoaderImpl$$Lambda$236/348558229.onChange(Unknown Source) [HotClassLoaderImpl.class:?]
	at ch.vorburger.hotea.watchdir.QuietPeriodListener.lambda$0(QuietPeriodListener.java:45) [QuietPeriodListener.class:?]
	at ch.vorburger.hotea.watchdir.QuietPeriodListener$$Lambda$282/785420076.run(Unknown Source) [QuietPeriodListener.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_40]
	at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1099) ~[CauseTracker.class:?]
	... 22 more
```

**Comment by kenzierocks** [comment]
You should not be setting blocks off of the server thread, MC isn't thread safe.

**Comment by vorburger** [comment]
@kenzierocks thank you. I' just looked around further, and found https://docs.spongepowered.org/master/en-GB/plugin/scheduler.html - presumably that is this the appropriate API in Sponge to "submit something to be done on the 'Server thread' whenever it can next" which I was looking for, like [SWT's Display asyncE‌xec](https://wiki.eclipse.org/FAQ_Why_do_I_get_an_invalid_thread_access_exception%3F), or [Swing's invokeLater](https://docs.oracle.com/javase/7/docs/api/javax/swing/SwingUtilities.html#invokeLater(java.lang.Runnable)) or [JavaFX's Platform runLater](http://docs.oracle.com/javafx/2/api/javafx/application/Platform.html#runLater(java.lang.Runnable)).

New https://github.com/SpongePowered/SpongeCommon/issues/608 enhancement opened re. auto detection.

Closing this then.
