### ISSUE TITLE
World corruption from scoreboards error

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeCommon#617]
While working with scoreboards I caused an error and upon restarting the server found that it now crashed while loading the scoreboard data. I boiled it down to the following code which while evidently is wrong should not be corrupting the world.

```java
Objective objective = Objective.builder().criterion(Criteria.DUMMY).objectiveDisplayMode(ObjectiveDisplayModes.INTEGER).name("sidebar")
        .displayName(Text.of("Sidebar")).build();
Score score = objective.getOrCreateScore(Text.of("Text"));
score.setScore(1);
Scoreboard scoreboard = event.getTargetEntity().getScoreboard();
scoreboard.updateDisplaySlot(objective, DisplaySlots.SIDEBAR);
Score score2 = objective.getOrCreateScore(Text.of("Another"));
objective.removeScore(score);
```
Which causes the error
```
java.lang.IllegalStateException: Attempting to remove an score without an entry!
	at org.spongepowered.common.scoreboard.SpongeScore.removeScoreFor(SpongeScore.java:112) ~[SpongeScore.class:?]
	at org.spongepowered.common.scoreboard.SpongeObjective.removeScore(SpongeObjective.java:209) ~[SpongeObjective.class:?]
```
Here is the resultant scoreboard.dat file which will fail to load.

![scoreboards.dat](http://puu.sh/nXUbW/431db67174.png)

The error thrown at startup is:

```
java.lang.NullPointerException
	at net.minecraft.scoreboard.ServerScoreboard.getValueFromObjective(ServerScoreboard.java:260) ~[ServerScoreboard.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.readScores(ScoreboardSaveData.java:184) ~[ScoreboardSaveData.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.readFromNBT(ScoreboardSaveData.java:49) ~[ScoreboardSaveData.class:?]
	at net.minecraft.scoreboard.ScoreboardSaveData.setScoreboard(ScoreboardSaveData.java:33) ~[ScoreboardSaveData.class:?]
	at net.minecraft.world.WorldServer.init(WorldServer.java:138) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:437) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:248) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

(Tested with SpongeVanilla 1.8.9-4.1.0-BETA-279)

**Comment by Zidane** [comment]
@Aaron1011 

Damn kids.

**Comment by mcsnetworks** [comment]
He did it for the lulz.
