### ISSUE TITLE
`NullPointerException: uuid` while loading migrated Spigot world

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeCommon#648]
Confirmed to fail with the latest SpongeVanilla build 293 and SpongeForge build 1265.

Steps to reproduce:

1. Put a Spigot world (not the main world!) into the root folder of your Sponge server.
2. Delete all other worlds and configs in that root folder until you only have the files necessary for Sponge to run.
3. Let the plugin load the world with `server.loadWorld("copiedspigotworld")`. This throws the following exception or an filled Optional if there is a `level_sponge.dat` in the migrated world folder (see below).

Things I noticed:
- World migration seems to work fine. It says it migrated [1] world. That world is then also found in the "world" folder.
- The strange thing is that 1. there isn't a `level_sponge.dat` in the "world" folder until the server is shutdown and 2. there isn't a `level_sponge.dat` in the "world/copiedspigotworld" folder even after a restart.
- If I copy the default world's `level_sponge.dat` ("world") into "world/copiedspigotworld", the server loads the world fine and without any exception.

Stacktrace:
```
[22:17:31 ERROR] [Sponge]: Could not pass ClientConnectionEvent$Login$Impl to Pl
ugin{id=testplugin, name=Testplugin, source=mods\testplugin-0.1-SNAPSHOT.jar}
java.lang.NullPointerException: uuid
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:
229) ~[minecraft_server.1.8.9.jar:?]
        at org.spongepowered.common.registry.type.world.WorldPropertyRegistryMod
ule.isWorldRegistered(WorldPropertyRegistryModule.java:72) ~[WorldPropertyRegist
ryModule.class:1.8.9-4.1.0-BETA-293]
        at net.minecraft.server.MinecraftServer.loadWorld(SourceFile:680) ~[Mine
craftServer.class:?]
        at de.therasppie.testplugin.world.WorldManagerImpl.getOrLoad(WorldManagerImpl
.kt:18) ~[WorldManagerImpl.class:?]
        at de.therasppie.testplugin.listener.ConnectionListener.onLogin(ConnectionLis
tener.kt:18) ~[ConnectionListener.class:?]
        at org.spongepowered.common.event.listener.LoginListener_ConnectionListe
ner_onLogin3.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredLi
stener.java:86) ~[RegisteredListener.class:1.8.9-4.1.0-BETA-293]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventMan
ager.java:258) [SpongeEventManager.class:1.8.9-4.1.0-BETA-293]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventMan
ager.java:269) [SpongeEventManager.class:1.8.9-4.1.0-BETA-293]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:131) [S
pongeImpl.class:1.8.9-4.1.0-BETA-293]
        at net.minecraft.server.management.ServerConfigurationManager.initialize
ConnectionToPlayer(SourceFile:210) [lx.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.func_72355
_a(SourceFile:139) [lx.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(Sour
ceFile:110) [lo.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(Sourc
eFile:56) [lo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:221) [ek
.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:168) [ll
.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:206) [Mi
necraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFil
e:299) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) [Mi
necraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftSe
rver.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
```

Thanks in advance!

**Comment by Zidane** [comment]
The world migrator's purpose is to solely migrate the folder into the right spot. It is NOT a world manager, it doesn't load the world. It doesn't generate any sponge files (since you didn't load it).

Now the actual bug where loadWorld isn't creating a UUID is valid and I'll look into it. Thanks for letting me know.

**Comment by TheRaspPie** [comment]
After searching through a lot of code, I think this is the issue:

As `worldInfo.getUniqueId()` is null in https://github.com/SpongePowered/SpongeCommon/blob/cfec312a67e61bc4f718846d6c8a79170b065ff5/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L680 the mistake must be in the lines above.

The `uuid` field in `MixinWorldInfo` is never initialized if the else branch (https://github.com/SpongePowered/SpongeCommon/blob/cfec312a67e61bc4f718846d6c8a79170b065ff5/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L661) is taken.

`loadAllWorlds` seems to generate a random UUID if the world doesn't have one, but this method doesn't get called for non-Sponge worlds.
