### ISSUE TITLE
Exception when attempting to obtain the PassableProperty status via getProperty

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#650]
```java
java.lang.UnsupportedOperationException: A method was invoked on a dummy class, due to the static field AIR not being initialized (most likely in a CatalogType-related class).
Method: public abstract java.util.Optional org.spongepowered.api.data.property.PropertyHolder.getProperty(java.lang.Class)
        at org.spongepowered.api.util.dummy.BlockType$DummyClass.getProperty(Unknown Source) ~[?:?]
        at com.skelril.Pitfall.sponge.PitfallPlugin.onStart(PitfallPlugin.java:95) ~[PitfallPlugin.class:?]
        at org.spongepowered.common.event.listener.GameStartingServerEventListener_PitfallPlugin_onStart13.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8.9-1808-4.1.0-BETA-1265]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1265]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:282) [SpongeModEventManager.class:1.8.9-1808-4.1.0-BETA-1265]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:183) [SpongeMod.class:1.8.9-1808-4.1.0-BETA-1265]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.8.9.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.8.9.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$0(LoadController.java:53) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:787) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:284) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:281) [ko.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
```

Triggering code:
https://github.com/Skelril/Pitfall-2/blob/sponge/src/main/java/com/skelril/Pitfall/sponge/PitfallPlugin.java#L95

This worked previously.

**Comment by simon816** [comment]
Looks like this is caused by the addition of a `BlockSnapshot.NONE`, the `BlockTypes.AIR` is accessed before it is remapped
https://github.com/SpongePowered/SpongeCommon/commit/dfae1e0018e9326248821b5ea46a7b6259e9acaa#diff-42cddc4a65ed4b8ef843be2329b4bbd6R146
