### ISSUE TITLE
Crash when too close to world limit border

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeCommon#651]
In the 'org.spongepowered.common.world.storage.SpongeChunkLayout' file, there is a maximum of coordinates in the world. In the vanilla server, when you go further than this limit, there is void, but 
it works. In SpongeCommon it throws an exception: 

Command to teleport: `/tp @p 29999999 100 29999999`.

```
[10:56:49 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:177) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) ~[ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid1875001, -6
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.9.jar:?]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63) ~[ChunkPrimerBuffer.class:1.8.9-4.1.0-BETA-293]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57) ~[ChunkPrimerBuffer.class:1.8.9-4.1.0-BETA-293]
    at org.spongepowered.common.world.gen.SpongeChunkProvider.func_73154_d(SpongeChunkProvider.java:206) ~[SpongeChunkProvider.class:1.8.9-4.1.0-BETA-293]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:87) ~[ld.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(SourceFile:116) ~[ld.class:?]
    at net.minecraft.world.World.func_72964_e(SourceFile:277) ~[adm.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(SourceFile:327) ~[le.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(SourceFile:202) ~[le.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:173) ~[MinecraftServer.class:?]
    ... 4 more
```

When you restart the server and try to log in again.

```
[10:57:16 WARN]: Failed to handle packet for /127.0.0.1:45363
net.minecraft.util.ReportedException: Exception generating new chunk
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:96) ~[ld.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(SourceFile:116) ~[ld.class:?]
    at net.minecraft.world.World.func_72964_e(SourceFile:277) ~[adm.class:?]
    at org.spongepowered.common.event.CauseTracker.processSpawnEntity(CauseTracker.java:976) ~[CauseTracker.class:1.8.9-4.1.0-BETA-293]
    at net.minecraft.world.World.spawnEntity(SourceFile:315) ~[adm.class:?]
    at net.minecraft.world.World.func_72838_d(SourceFile:310) ~[adm.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.handler$playerLoggedIn2$0(SourceFile:537) ~[lx.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(SourceFile:265) ~[lx.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(SourceFile:274) ~[lx.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(SourceFile:139) ~[lx.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:110) ~[lo.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:56) ~[lo.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:221) ~[ek.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:168) [ll.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:206) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) [ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid1875000, 0
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125) ~[minecraft_server.1.8.9.jar:?]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63) ~[ChunkPrimerBuffer.class:1.8.9-4.1.0-BETA-293]
    at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57) ~[ChunkPrimerBuffer.class:1.8.9-4.1.0-BETA-293]
    at org.spongepowered.common.world.gen.SpongeChunkProvider.func_73154_d(SpongeChunkProvider.java:206) ~[SpongeChunkProvider.class:1.8.9-4.1.0-BETA-293]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:87) ~[ld.class:?]
    ... 18 more
[10:57:16 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:177) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) ~[ko.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalStateException: Cannot reuse while still in use
    at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[minecraft_server.1.8.9.jar:?]
    at org.spongepowered.common.util.gen.ByteArrayMutableBiomeBuffer.reuse(ByteArrayMutableBiomeBuffer.java:123) ~[ByteArrayMutableBiomeBuffer.class:1.8.9-4.1.0-BETA-293]
    at org.spongepowered.common.world.gen.SpongeChunkProvider.func_73154_d(SpongeChunkProvider.java:201) ~[SpongeChunkProvider.class:1.8.9-4.1.0-BETA-293]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:87) ~[ld.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(SourceFile:116) ~[ld.class:?]
    at net.minecraft.world.World.func_72964_e(SourceFile:277) ~[adm.class:?]
    at net.minecraft.world.SpawnerAnimals.func_180621_a(SourceFile:159) ~[adt.class:?]
    at net.minecraft.world.SpawnerAnimals.func_77192_a(SourceFile:80) ~[adt.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(SourceFile:182) ~[le.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:173) ~[MinecraftServer.class:?]
    ... 4 more
```

**Comment by Zidane** [comment]
I've made a fix here: https://github.com/SpongePowered/SpongeCommon/commit/bc5636b29dc14c9765546c03ecf362d660163395

Awaiting feedback before merge.

**Comment by advancid** [comment]
Sorry I gave you the wrong command (forgotten a 0), so your patch is not working. This is the good one: `/tp 29999999 100 29999999`.
Your patch threw this:

```
[12:56:19 ERROR]: Couldn't load chunk
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_77]
	at net.minecraft.world.chunk.Chunk.handler$onConstructed$0(SourceFile:174) ~[amy.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(SourceFile:84) ~[amy.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(SourceFile:267) ~[anj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(SourceFile:77) ~[anj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(SourceFile:64) ~[anj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(SourceFile:129) [ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:81) [ld.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(SourceFile:39) [lc$a.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:231) [lc.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(SourceFile:263) [lc.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(SourceFile:225) [lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.handler$playerLoggedIn2$0(SourceFile:561) [lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(SourceFile:265) [lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(SourceFile:276) [lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(SourceFile:141) [lx.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:110) [lo.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:56) [lo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:221) [ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:168) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:206) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[12:56:19 WARN]: Failed to handle packet for /127.0.0.1:56307
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:96) ~[ld.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(SourceFile:39) ~[lc$a.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(SourceFile:231) ~[lc.class:?]
	at net.minecraft.server.management.PlayerManager.func_72683_a(SourceFile:263) ~[lc.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72375_a(SourceFile:225) ~[lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.handler$playerLoggedIn2$0(SourceFile:561) ~[lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72377_c(SourceFile:265) ~[lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(SourceFile:276) ~[lx.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72355_a(SourceFile:141) ~[lx.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:110) ~[lo.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:56) ~[lo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:221) ~[ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:168) [ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:206) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_77]
	at net.minecraft.world.chunk.Chunk.handler$onConstructed$0(SourceFile:174) ~[amy.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(SourceFile:84) ~[amy.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(SourceFile:87) ~[amy.class:?]
	at org.spongepowered.common.world.gen.SpongeChunkProvider.func_73154_d(SpongeChunkProvider.java:240) ~[SpongeChunkProvider.class:1.8.9-4.1.0-BETA-0]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:87) ~[ld.class:?]
	... 17 more
[12:56:20 ERROR]: Couldn't load chunk
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_77]
	at net.minecraft.world.chunk.Chunk.handler$onConstructed$0(SourceFile:174) ~[amy.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(SourceFile:84) ~[amy.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(SourceFile:267) ~[anj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75822_a(SourceFile:77) ~[anj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75815_a(SourceFile:64) ~[anj.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73239_e(SourceFile:129) [ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:81) [ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(SourceFile:116) [ld.class:?]
	at net.minecraft.world.World.func_72964_e(SourceFile:277) [adm.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(SourceFile:327) [le.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(SourceFile:202) [le.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:173) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
[12:56:20 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:177) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:299) ~[ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:535) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:451) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IllegalStateException: Cannot reuse while still in use
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[minecraft_server.1.8.9.jar:?]
	at org.spongepowered.common.util.gen.ByteArrayMutableBiomeBuffer.reuse(ByteArrayMutableBiomeBuffer.java:123) ~[ByteArrayMutableBiomeBuffer.class:1.8.9-4.1.0-BETA-0]
	at org.spongepowered.common.world.gen.SpongeChunkProvider.func_73154_d(SpongeChunkProvider.java:201) ~[SpongeChunkProvider.class:1.8.9-4.1.0-BETA-0]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(SourceFile:87) ~[ld.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(SourceFile:116) ~[ld.class:?]
	at net.minecraft.world.World.func_72964_e(SourceFile:277) ~[adm.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(SourceFile:327) ~[le.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(SourceFile:202) ~[le.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:173) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by ryantheleach** [comment]
I'm looking for people to test this on the latest versions we support.

**Comment by ImMorpheus** [comment]
Step to reproduce:

1. `/tp 29998983 ~ 29998983`
2. Start flying toward x = 29999999
3. As soon as you approach the worldborder, the server crashes.

```
[14:56:17 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1947) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:404) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:680) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Chunk coordinates are not valid1874939, 1875000
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63) ~[ChunkPrimerBuffer.class:?]
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57) ~[ChunkPrimerBuffer.class:?]
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.generateChunk(SpongeChunkGenerator.java:246) ~[SpongeChunkGenerator.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:127) ~[ChunkProviderServer.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvideChunk$zpe000(PlayerChunkMapEntry.java:1097) ~[PlayerChunkMapEntry.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:102) ~[PlayerChunkMapEntry.class:?]
	at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:183) ~[PlayerChunkMap.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:224) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1943) ~[MinecraftServer.class:?]
	... 4 more
```

Crash report:

```
---- Minecraft Crash Report ----
// Oops.

Description: Exception generating new chunk

java.lang.IllegalArgumentException: Chunk coordinates are not valid1874939, 1875000
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63)
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.generateChunk(SpongeChunkGenerator.java:246)
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:127)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvideChunk$zpe000(PlayerChunkMapEntry.java:1097)
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:102)
	at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:183)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:224)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1943)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:404)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:680)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.getBlockStart(ChunkPrimerBuffer.java:63)
	at org.spongepowered.common.util.gen.ChunkPrimerBuffer.<init>(ChunkPrimerBuffer.java:57)
	at org.spongepowered.common.world.gen.SpongeChunkGenerator.generateChunk(SpongeChunkGenerator.java:246)

-- Chunk to be generated --
Details:
	Location: 1874939,1875000
	Position hash: 8053063681874939
	Generator: org.spongepowered.common.world.gen.SpongeChunkGenerator@6a4276d1
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:127)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvideChunk$zpe000(PlayerChunkMapEntry.java:1097)
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:102)
	at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:183)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:224)
```
