### ISSUE TITLE
IndexOutOfBoundsException in UserDiscoverer during startup

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#666]
Had an unusual error that was crashing an older SpongeForge build. I updated to the latest build (1286) and while it doesn't crash anymore, the following appears during startup.

```
[12:47:35] [Server thread/WARN] [Sponge/]: Error while getting profile for 4db05a84-8505-44d1-81be-d4f7003a0842
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_77]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_77]
	at org.spongepowered.common.service.user.UserDiscoverer.getProfileFromServer(UserDiscoverer.java:207) [UserDiscoverer.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:188) [UserDiscoverer.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.common.service.user.UserDiscoverer.findByUuid(UserDiscoverer.java:91) [UserDiscoverer.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:58) [SpongeUserStorageService.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.common.service.user.SpongeUserStorageService.getOrCreate(SpongeUserStorageService.java:70) [SpongeUserStorageService.class:1.8.9-1808-4.1.0-BETA-1286]
	at net.minecraft.world.chunk.Chunk.userForUUID(Chunk.java:901) [amy.class:?]
	at net.minecraft.world.chunk.Chunk.getBlockNotifier(Chunk.java:658) [amy.class:?]
	at net.minecraft.world.World.getNotifier(World.java:812) [adm.class:?]
	at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:244) [adm.class:?]
	at net.minecraft.world.World.createSpongeBlockSnapshot(World.java:159) [adm.class:?]
	at org.spongepowered.common.event.CauseTracker.updateTickBlock(CauseTracker.java:1120) [CauseTracker.class:1.8.9-1808-4.1.0-BETA-1286]
	at net.minecraft.world.WorldServer.redirect$onUpdateTick$0(WorldServer.java:158) [le.class:?]
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:611) [le.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219) [le.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_77]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_77]
	at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:54) ~[UniqueIdQuery$SingleGet.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:43) ~[UniqueIdQuery$SingleGet.class:1.8.9-1808-4.1.0-BETA-1286]
	at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$24(Functional.java:131) ~[Functional.class:1.8.9-1808-4.1.0-BETA-1286]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_77]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_77]
	... 1 more

**Comment by modwizcode** [comment]
Problem is being thrown from here. https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/service/user/UserDiscoverer.java#L203-L217

Cause is https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/profile/query/UniqueIdQuery.java#L54 not verifying that here is an element. I would assume this just needs a `size()` check.

**Comment by simon816** [comment]
Hmm I seem to remember I never intended for `UserDiscoverer` to perform lookups, I think we should remove the lookup.
It's only supposed to check for cached data.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/1e33dfa586ddaa256028d7bcd35675a46ee5806b.
