### ISSUE TITLE
Entity Already Tracked

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#678]
```
[17:00:27] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:225) ~[la.class:?]
        at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:148) ~[la.class:?]
        at net.minecraft.world.WorldManager.func_72703_a(SourceFile:30) ~[lb.class:?]
        at net.minecraft.world.World.func_72923_a(World.java:1135) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:945) ~[le.class:?]
        at net.minecraft.world.World.onSpongeEntityAdded(World.java:576) ~[adm.class:?]
        at org.spongepowered.common.event.CauseTracker.processSpawnEntity(CauseTracker.java:1087) ~[CauseTracker.class:1.8.9-1808-4.1.0-BETA-0]
        at net.minecraft.world.World.spawnEntity(World.java:314) ~[adm.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.runAttack(ShnugglesPrimeInstance.java:467) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.runRandomAttack(ShnugglesPrimeInstance.java:264) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeInstance.run(ShnugglesPrimeInstance.java:129) ~[ShnugglesPrimeInstance.class:?]
        at com.skelril.skree.content.zone.group.shnugglesprime.ShnugglesPrimeManager.run(ShnugglesPrimeManager.java:397) ~[ShnugglesPrimeManager.class:?]
        at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138) ~[Task$Builder.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177) ~[SchedulerBase.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:66) ~[SyncScheduler.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:160) ~[SchedulerBase.class:1.8.9-1808-4.1.0-BETA-0]
        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_03-Ubuntu]
        at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:104) [SchedulerBase.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:41) [SyncScheduler.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:191) [SpongeScheduler.class:1.8.9-1808-4.1.0-BETA-0]
        at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:220) [SpongeMod.class:1.8.9-1808-4.1.0-BETA-0]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:84) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:60) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:266) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:594) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_03-Ubuntu]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:192) ~[la.class:?]
        ... 29 more
```

I believe this relates to: https://github.com/SpongePowered/SpongeCommon/commit/d07457a7b552919581595649bb7e2767d8e92e88

**Comment by simon816** [comment]
@DarkArc Looks like it's an error on your side
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/zone/group/shnugglesprime/ShnugglesPrimeInstance.java#L467
should be `spawnEntity(potion, [...]`

**Comment by ryantheleach** [comment]
@simon816 Should it not instead warn the programmer with a better exception, or return false for an unsuccessful spawn?

I'd opt for a more descriptive exception as I can't see a reason for spawning a single entity twice.

**Comment by DarkArc** [comment]
Haha oops, that's embarrassing, surprised I didn't notice this wasn't working before.

**Comment by Zidane** [comment]
@simon816 

If an Entity is already spawned, throw an Exception here.
