### ISSUE TITLE
NPE on MessageChannel.asMutable

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#709]
version SpongeForge 293faf0420a93106a42ec3e6ad8581cc0e19934a

https://gist.github.com/ryantheleach/629a35bb90f176dc0a28e207d02a0d2e

I suspect it's due to the delegateMessageChannels members collection being immutable / a view of the hashmap, and not having a defined add / addAll method.
```
[07:33:43] [Server thread/INFO]: Player515[local:E:d4c142a2] logged in with entity id 216 in BedTest(0) at (98.02450814469864, 70.39029388578963, 234.43825235347376)
[07:33:53] [Server thread/ERROR] [Sponge]: Could not pass PlayerLoggedInEvent to org.spongepowered.mod.plugin.SpongeModPluginContainer@37e0c4db
java.lang.NullPointerException
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[?:1.8.0_66]
	at org.spongepowered.api.text.channel.impl.DelegateMutableMessageChannel.<init>(DelegateMutableMessageChannel.java:50) ~[DelegateMutableMessageChannel.class:?]
	at TextTesting$FactionsMessageChannel.asMutable(TextTesting.java:43) ~[TextTesting$FactionsMessageChannel.class:?]
	at TeamChat.onChat(TeamChat.java:46) ~[TeamChat.class:?]
	at org.spongepowered.common.event.listener.MessageChannelEventListener_TeamChat_onChat2.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:239) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:199) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:279) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:251) [SpongeModEventManager.class:?]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:128) [SpongeImpl.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:325) [ServerConfigurationManager.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:242) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:193) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:310) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:204) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:800) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by simon816** [comment]
Don't return `null` here: https://gist.github.com/ryantheleach/629a35bb90f176dc0a28e207d02a0d2e#file-texttesting-java-L39

**Comment by ryantheleach** [comment]
Sorry I should have picked up on that, I'm blind.
