### ISSUE TITLE
[1.9.4] Intended to capture dropped item entities!

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#730]
@gabizou I don't really know how to fix it, but this is from the 1.9.4 branch:

```
/****************************************************************/
/*          Exception trying to process over a phase!           */
/****************************************************************/
/* PhaseContext :                                               */
/*         - Name: EMPTY                                        */
/*           Object: EMPTY                                      */
/* Stacktrace:                                                  */
/****************************************************************/
[14:28:51 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Intended to capture dropped item entities! Please analyze the current phase context. 
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:132) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:340) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.IllegalStateException: Intended to capture dropped item entities! Please analyze the current phase context. 
        at org.spongepowered.common.event.tracking.phase.util.PhaseUtil.lambda$throwWithContext$0(PhaseUtil.java:45) ~[PhaseUtil.class:1.9.4-5.0.0-BETA-0]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_71]
        at org.spongepowered.common.event.tracking.PhaseContext.getCapturedItems(PhaseContext.java:147) ~[PhaseContext.class:1.9.4-5.0.0-BETA-0]
        at org.spongepowered.common.event.tracking.phase.TrackingPhase.attemptEntitySpawnCapture(TrackingPhase.java:256) ~[TrackingPhase.class:1.9.4-5.0.0-BETA-0]
        at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:407) ~[CauseTracker.class:1.9.4-5.0.0-BETA-0]
        at net.minecraft.world.WorldServer.func_72838_d(SourceFile:547) ~[lq.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_184816_a(SourceFile:709) ~[zj.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_146097_a(SourceFile:696) ~[zj.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70436_m(SourceFile:553) ~[zi.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(SourceFile:409) ~[ls.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(SourceFile:394) ~[sa.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70097_a(SourceFile:873) ~[zj.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(SourceFile:457) ~[ls.class:?]
        at net.minecraft.entity.EntityLivingBase.func_180430_e(SourceFile:972) ~[sa.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_180430_e(SourceFile:1629) ~[zj.class:?]
        at net.minecraft.block.Block.func_180658_a(SourceFile:690) ~[ajt.class:?]
        at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$0(SourceFile:924) ~[rr.class:?]
        at net.minecraft.entity.Entity.func_184231_a(SourceFile:874) ~[rr.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184231_a(SourceFile:206) ~[sa.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(SourceFile:620) ~[ls.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(SourceFile:509) ~[mc.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126) ~[iu.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(SourceFile:57) ~[iu$a.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:100) ~[PacketUtil.class:1.9.4-5.0.0-BETA-0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fj$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fj$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_71]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_71]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by Minecrell** [comment]
More fun stuff, seems like it needs some changes for 1.9.4:

```
/****************************************************************/
/*          Exception trying to process over a phase!           */
/****************************************************************/
/* PhaseContext :                                               */
/*         - Name: EMPTY                                        */
/*           Object: EMPTY                                      */
/* Stacktrace:                                                  */
/****************************************************************/
[14:31:24 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:164) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:340) ~[lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]
Caused by: java.lang.IllegalStateException: Intended to capture block changes, but there is no list available! Please analyze the current phase context. 
        at org.spongepowered.common.event.tracking.phase.util.PhaseUtil.lambda$throwWithContext$0(PhaseUtil.java:45) ~[PhaseUtil.class:1.9.4-5.0.0-BETA-0]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_71]
        at org.spongepowered.common.event.tracking.PhaseContext.getCapturedBlocks(PhaseContext.java:175) ~[PhaseContext.class:1.9.4-5.0.0-BETA-0]
        at org.spongepowered.common.event.tracking.TrackingUtil.trackBlockChange(TrackingUtil.java:186) ~[TrackingUtil.class:1.9.4-5.0.0-BETA-0]
        at org.spongepowered.common.event.tracking.CauseTracker.setBlockState(CauseTracker.java:331) ~[CauseTracker.class:1.9.4-5.0.0-BETA-0]
        at net.minecraft.world.WorldServer.func_180501_a(SourceFile:566) ~[lq.class:?]
        at net.minecraft.world.World.func_175656_a(SourceFile:372) ~[aht.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(SourceFile:409) ~[lq.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(SourceFile:218) ~[lq.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:160) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by Zidane** [comment]
@gabizou has covered these two.
