### ISSUE TITLE
Issues if player logs out inside a minecart

### ISSUE THREAD

**Issue by AKPWebDesign** [SpongePowered/SpongeCommon#769]
If a player logs out while inside of a minecart, then logs back in, the following error is encountered, and the player will fail to log in. The minecart is then removed from the world, and the next time the player logs in, they will be inside of the block that the minecart was sitting on top of. I tested this just now with the latest code on the master branch.

```
java.lang.ClassCastException: net.minecraft.entity.item.EntityMinecartEmpty cannot be cast to net.minecraft.entity.player.EntityPlayer
	at org.spongepowered.common.event.CauseTracker.processSpawnEntity(CauseTracker.java:1003) ~[CauseTracker.class:?]
	at net.minecraft.world.World.spawnEntity(World.java:1285) ~[World.class:?]
	at net.minecraft.world.World.handler$onSpawnEntityInWorld$0(World.java:1275) ~[World.class:?]
	at net.minecraft.world.World.spawnEntityInWorld(World.java) ~[World.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:339) ~[ServerConfigurationManager.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:148) ~[ServerConfigurationManager.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64) ~[NetHandlerLoginServer.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:287) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:172) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:206) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:356) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

I want to clarify what I mean by "they will be inside of the block that the minecart was sitting on top of."

If the player is in the minecart pictured below when they log out, they will be standing on top of the glass block (and partially inside the brick block) when they log back in. If there is no block two blocks down from where the minecart was, the player will log in and fall down to the next block.

![Image of minecart/block layout](https://i.imgur.com/NC6IPk5.png)

**Comment by Zidane** [comment]
Cannot reproduce in neither SinglePlayer or Server (both implementations)

**Comment by bloodmc** [comment]
You need to update to LATEST build. You are on an outdated sponge build.

**Comment by AKPWebDesign** [comment]
Haha, yeah. I mean, when I opened this last week, I was... :stuck_out_tongue: 
Glad it's been fixed since then.
