### ISSUE TITLE
[1.9.4] NPE When stopping the server

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#781]
```
[16:42:01] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException
        at org.spongepowered.common.world.WorldManager.lambda$static$1(WorldManager.java:117) ~[WorldManager.class:1.9.4-1954-5.0.0-BETA-1418]
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:1.8.0_91]
        at java.util.TimSort.sort(TimSort.java:220) ~[?:1.8.0_91]
        at java.util.Arrays.sort(Arrays.java:1438) ~[?:1.8.0_91]
        at java.util.List.sort(List.java:478) ~[?:1.8.0_91]
        at org.spongepowered.common.world.WorldManager.reorderWorldsVanillaFirst(WorldManager.java:774) ~[WorldManager.class:1.9.4-1954-5.0.0-BETA-1418]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:426) ~[WorldManager.class:1.9.4-1954-5.0.0-BETA-1418]
        at net.minecraft.server.MinecraftServer.redirect$onSetWorldUnload$0(MinecraftServer.java:90) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:405) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:522) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
``

**Comment by DarkArc** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/675

**Comment by Zidane** [comment]
Will be fixed in next commit(s) from me to common.
