### ISSUE TITLE
[1.9.4] NPE When starting the server

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#782]
```
java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: ./Main
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:576) ~[WorldManager.class:1.9.4-1954-5.0.0-BETA-1418]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:325) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:263) ~[lb.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.nio.file.FileAlreadyExistsException: ./Main
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88) ~[?:1.8.0_91]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_91]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_91]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_91]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_91]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_91]
        at java.nio.file.Files.createDirectories(Files.java:727) ~[?:1.8.0_91]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:574) ~[WorldManager.class:1.9.4-1954-5.0.0-BETA-1418]
        ... 4 more
```

Interestingly enough, I didn't run into this issue when I moved Main to Main2, and had it generate Main from scratch, even on subsequent reboots. It only seems to happen when working with the 1.8.9 world directory.

**Comment by DarkArc** [comment]
Ah, I think I know what the problem is, my "Main" directory is a symlink.

**Comment by Zidane** [comment]
Alright I found this bug ticket on OpenJDK: https://bugs.openjdk.java.net/browse/JDK-8130464

Technically the commenters are correct. I've wrote the following code:

```
        final Path currentSavesDir = server.anvilFile.toPath().resolve(server.getFolderName());
        try {
            // Symlink needs special handling
            if (Files.isSymbolicLink(currentSavesDir)) {
                final Path actualPathLink = Files.readSymbolicLink(currentSavesDir);
                if (Files.notExists(actualPathLink)) {
                    // TODO Need to test symlinking to see if this is even legal...
                    Files.createDirectories(actualPathLink);       
                } else if (!Files.isDirectory(actualPathLink)) {
                    throw new IOException("Saves directory [" + currentSavesDir + "] symlinked to [" + actualPathLink + "] is not a directory!");                    
                }
            } else {
                if (!Files.isSymbolicLink(currentSavesDir)) {
                    Files.createDirectories(currentSavesDir);
                }
            }
        } catch (IOException ioe) {
            throw new RuntimeException(ioe);
        }
```

Haven't tested it yet but I think it is correct.
