### ISSUE TITLE
[1.9.4] Players cannot connect to plugin created worlds

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#783]
If a player changes to a world created by a Sponge plugin, disconnects, and attempts to join the game again, they will be forever on the loading screen. No exceptions are logged.

**Comment by Aaron1011** [comment]
@DarkArc: I can't seem to reproduce this.

**Comment by DarkArc** [comment]
Hmm... that's very strange...

**Comment by DarkArc** [comment]
@Aaron1011 I figured it out You need SpongeForge on the client, and the following exceptions occurs client side:
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bcd.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.play.server.SPacketEntity.func_149065_a(SourceFile:161) ~[gw.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147259_a(NetHandlerPlayClient.java:582) ~[bkq.class:?]
	at net.minecraft.network.play.server.SPacketEntity.func_148833_a(SourceFile:152) ~[gw.class:?]
	at net.minecraft.network.play.server.SPacketEntity$S15PacketEntityRelMove.func_148833_a(SourceFile:67) ~[gw$a.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:125) ~[PacketUtil.class:1.9.4-1954-5.0.0-BETA-1418]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) ~[fj$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fj$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more
```

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/d3c229cafa0c7010f8e601e4685e2f5b945d2c88.
