### ISSUE TITLE
[1.10] Opening creative mode inventory, the provided entity is null

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#809]
Exception:
```
[15:11:55] [Server thread/ERROR] [Sponge]: Could not pass CreativeInventoryEvent$Drop$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@3a06a3e8  
java.lang.NullPointerException                                                                                                                                
        at com.skelril.skree.content.zone.ZoneApplicableListener.isApplicable(ZoneApplicableListener.java:24) ~[ZoneApplicableListener.class:?]               
        at com.skelril.skree.content.zone.ZoneNaturalSpawnBlocker.onEntitySpawn(ZoneNaturalSpawnBlocker.java:31) ~[ZoneNaturalSpawnBlocker.class:?]           
        at org.spongepowered.common.event.listener.SpawnEntityEventListener_ZoneNaturalSpawnBlocker_onEntitySpawn121.handle(Unknown Source) ~[?:?]            
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10-1983-bleeding-1.10-BETA-0]    
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:225) [SpongeModEventManager.class:1.10-1983-bleeding-1.10-BETA-0]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:208) [SpongeModEventManager.class:1.10-1983-bleeding-1.10-BETA-0]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:253) [SpongeModEventManager.class:1.10-1983-bleeding-1.10-BETA-0]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:238) [SpongeModEventManager.class:1.10-1983-bleeding-1.10-BETA-0]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) [SpongeImpl.class:1.10-1983-bleeding-1.10-BETA-0]                               
        at org.spongepowered.common.event.SpongeCommonEventFactory.callCreativeDropInventoryEvent(SpongeCommonEventFactory.java:603) [SpongeCommonEventFactory
.class:1.10-1983-bleeding-1.10-BETA-0]                                                                                                                        
        at net.minecraft.network.NetHandlerPlayServer.func_147344_a(NetHandlerPlayServer.java:467) [me.class:?]
        at net.minecraft.network.play.client.CPacketCreativeInventoryAction.func_148833_a(SourceFile:23) [jf.class:?]
        at net.minecraft.network.play.client.CPacketCreativeInventoryAction.func_148833_a(SourceFile:9) [jf.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:121) [PacketUtil.class:1.10-1983-bleeding-1.10-BETA-0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Relevant source:
```
/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.skelril.skree.content.zone;

import org.spongepowered.api.entity.Entity;
import org.spongepowered.api.world.Location;
import org.spongepowered.api.world.World;

import java.util.Optional;
import java.util.function.Function;

public class ZoneApplicableListener<T> {
    private final Function<Location<World>, Optional<T>> applicabilityFunct;

    public ZoneApplicableListener(Function<Location<World>, Optional<T>> applicabilityFunct) {
        this.applicabilityFunct = applicabilityFunct;
    }

    public boolean isApplicable(Entity entity) {
        return isApplicable(entity.getLocation()); // Line 24
    }

    public boolean isApplicable(Location<World> location) {
        return getApplicable(location).isPresent();
    }

    public Optional<T> getApplicable(Entity entity) {
        return getApplicable(entity.getLocation());
    }

    public Optional<T> getApplicable(Location<World> location) {
        return applicabilityFunct.apply(location);
    }
}
```

**Comment by Zidane** [comment]
Closing as this isn't an issue anymore.
