### ISSUE TITLE
[1.8.9] Netty AssertionError on player join

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeCommon#820]
This exception was generated on the latest build of SpongeForge 4.2.0 (but is caused by Common code). Stack trace follows:

```
[11:49:43] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:203) ~[EmbeddedChannel.class:?]
	at org.spongepowered.common.world.DimensionManager.sendDimensionRegistration(DimensionManager.java:159) ~[DimensionManager.class:1.8.9-1890-4.2.0-BETA-1511]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:276) ~[lx.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:239) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:54) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:190) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:289) ~[ek.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:189) ~[ll.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:724) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

Obviously the JVM needs the `-ea` flag passed to replicate this.

**Comment by caseif** [comment]
Moved to [SpongeForge/#720](https://github.com/SpongePowered/SpongeForge/issues/720).
