### ISSUE TITLE
Rare crash bug

### ISSUE THREAD

**Issue by inklit** [SpongePowered/SpongeCommon#835]
This has happened once, not sure if it's a very serious issue but it seems to be incredibly rare.
The server randomly stopped with "Server Closed." as usual "Exception in server tick loop" crashes do.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1547.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/9/16 7:31 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at co.aikar.util.JSONUtil.mapArray(JSONUtil.java:93)
	at co.aikar.timings.TimingHistory.lambda$new$4(TimingHistory.java:100)
	at co.aikar.timings.TimingHistory$$Lambda$464/123348457.apply(Unknown Source)
	at co.aikar.util.JSONUtil.mapArrayToObject(JSONUtil.java:109)
	at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:99)
	at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:101)
	at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$0(MinecraftServer.java:1103)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 2.6.32-042stab116.2
	Java Version: 1.8.0_45-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1149924720 bytes (1096 MB) / 2679734272 bytes (2555 MB) up to 3224436736 bytes (3075 MB)
	JVM Flags: 4 total; -Xmx3100M -Xincgc -XX:ParallelGCThreads=3 -XX:MaxPermSize=128m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.22.6} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	sponge{1.8.9-1890-4.2.0-BETA-1547} [SpongeForge] (spongeforge-1.8.9-1890-4.2.0-BETA-1547.jar) 
	UCHIJAAAA	<CCTweaks ASM>{1.0.1} [<CCTweaks ASM>] (minecraft.jar) 
	UCHIJAAAA	io.github.hsyyid.adminshop{1.8.1} [AdminShop] (AdminShop-1.8.9-1.8.1-universal.jar) 
	UCHIJAAAA	ComputerCraft{1.79} [ComputerCraft] (ComputerCraft1.79.jar) 
	UCHIJAAAA	CCTweaks{1.0.1} [CCTweaks] (CCTweaks-1.8.9-1.0.1.jar) 
	UCHIJAAAA	chunkloaderz{1.0.3} [ChunkLoaderZ] (ChunkLoaderZ-1.8.9-1.0.3.jar) 
	UCHIJAAAA	io.github.hsyyid.essentialcmds{@project.informativeVersion@} [EssentialCmds] (EssentialCmds-1.8.9-8.1.12-universal.jar) 
	UCHIJAAAA	griefprevention{1.0} [GriefPrevention] (griefprevention-1.8.9-1.0-22.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	JEI{2.28.9.176} [Just Enough Items] (jei_1.8.9-2.28.9.176.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	MoreFurnaces{1.5.1} [More Furnaces] (MoreFurnaces-1.5.1-MC1.8.9.jar) 
	UCHIJAAAA	nuvotifier{2.3.2.2} [NuVotifier] (nuvotifier-universal-2.3.2.2.jar) 
	UCHIJAAAA	OpenComputers{1.5.22.6} [OpenComputers] (OpenComputers-MC1.8.9-1.5.22.6.jar) 
	UCHIJAAAA	ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	totaleconomy{1.4.1} [Total Economy] (TotalEconomy-v1.4.1.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.8.9-6.1.1-dist.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.8.9-1890-4.2.0-BETA-1547.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.5.22.6.jar)
  li.cil.oc.common.asm.ClassTransformer
TweaksLoadingPlugin (CCTweaks-1.8.9-1.0.1.jar)
  org.squiddev.cctweaks.core.asm.ASMTransformer
	Profiler Position: N/A (disabled)
	Player Count: 5 / 50; [EntityPlayerMP['Autisterino'/829, l='world', x=3277.30, y=46.00, z=1422.30], EntityPlayerMP['Oeed'/2661, l='world', x=5697.82, y=78.00, z=2603.36], EntityPlayerMP['TehRockettek'/129278, l='world', x=5983.87, y=81.25, z=2733.26], EntityPlayerMP['BTC'/158254, l='world', x=3307.15, y=77.27, z=1441.23], EntityPlayerMP['alsacchi'/187075, l='world', x=3300.98, y=63.00, z=1433.93]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

I'm not 100% sure who is at fault here, but I figure that it's a problem that can be fixed in SpongeCommon because I believe that SpongeCommon is where the co.aikar.timings is implemented (?).
I figure this is a good place to start at the very least.

This is probably just an issue with aikar, and if it is please let me know and I will close this and contact aikar about it.

**Comment by zml2008** [comment]
This certainly has *something* to do with @Aikar's timings, but I'm not sure exactly what's triggering it. It would probably be worthwhile for him to look at this issue though.

**Comment by aikar** [comment]
The issue is not with timings, but in that something is trying to add to Timings async

**Comment by zml2008** [comment]
So yeah, timings only really make sense from the main thread. Why do we have anything but startTimingIfSync and stopTimingIfSync -- what is the use in allowing folks to start timings from other threads?

**Comment by aikar** [comment]
For when you don't know (Plugins)

**Comment by simon816** [comment]
This is not caused by an async timing call. You can see it's in the tick method
`at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$0(MinecraftServer.java:1103)`
The problem appears to be `world.getLoadedChunks()` is being modified when timings is saving the data

https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/co/aikar/timings/TimingHistory.java#L100

**Comment by aikar** [comment]
That would imply something is causing a chunk to load async.

One thing I did in paper is that if this ever happens, to force it sync:

https://github.com/PaperMC/Paper/commit/dfd19063f972b3542721e8a5328eb2342f9559d2

**Comment by inklit** [comment]
This has happened a few more times, and I think it's somehow related to chunk loaders.

**Comment by inklit** [comment]
Since updating SpongeForge, this has not happened in three days now when it used to happen about 3 times per day.
I think that this bug is fixed.
If it happens again, I'll make sure to let you guys know and it can be re-opened.

**Comment by inklit** [comment]
Looks like it's happening again. Nevermind. It's still a valid bug.

**Comment by Zidane** [comment]
I've went hours upon hours of chunk loading and cannot reproduce this.
