### ISSUE TITLE
An error occurred while receiving the object "Player" from event "DropItemEvent.Destruct"

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#871]
An error occurred while receiving the object "Player" from event "DropItemEvent.Destruct"

Code:
```
    @Listener
    public void onDropItem(DropItemEvent.Destruct event) {
        logger = getLogger();
        logger.info("EventDropItem.Destruct cause:" + "\n" + event.getCause().toString());
        //String 24
        logger.info(event.getCause().first(Player.class).get().getName());

    }
```

Result code (error):
```
[19:05:24] [Server thread/INFO] [grave]: EventDropItem.Destruct cause:
Cause[{Name=Source, Object={EntitySpawnCause{SpawnType=SpongeSpawnType{id=DroppedItem, name=DroppedItem}, EntitySnapshot=EntityPlayerMP['Azat'/98, l='world', x=298,26, y=68,00, z=269,94]}}}, {Name=DamageSource, Object={DamageSource{Name=outOfWorld, Type=void}}}]
[19:05:24] [Server thread/ERROR] [Sponge]: Could not pass DropItemEvent$Destruct$Impl to Plugin{id=grave, name=Grave, version=0.1.0, description=This plugin adds the grave., url=https://github.com/Azatik/Grave/, authors=[Azatik], source=mods\Grave.jar}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:1.8.0_101]
	at io.github.azatik.grave.events.EventDropItem.onDropItem(EventDropItem.java:24) ~[EventDropItem.class:?]
	at org.spongepowered.common.event.listener.DestructListener_EventDropItem_onDropItem6.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:303) ~[SpongeEventManager.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:316) ~[SpongeEventManager.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:138) ~[SpongeImpl.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.tracking.phase.EntityPhase$State$1.lambda$unwind$264(EntityPhase.java:182) ~[EntityPhase$State$1.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.tracking.CapturedMultiMapSupplier.ifPresentAndNotEmpty(CapturedMultiMapSupplier.java:60) [CapturedMultiMapSupplier.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.tracking.phase.EntityPhase$State$1.unwind(EntityPhase.java:164) [EntityPhase$State$1.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.tracking.phase.EntityPhase.unwind(EntityPhase.java:462) [EntityPhase.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:165) [CauseTracker.class:1.10.2-5.0.0-BETA-99]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(SourceFile:457) [sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(SourceFile:887) [zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(SourceFile:456) [lu.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(SourceFile:158) [sf.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) [an.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(SourceFile:82) [k.class:?]
	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:150) [MinecraftCommandWrapper.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:136) [MinecraftCommandWrapper.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) [SimpleDispatcher.class:1.10.2-5.0.0-BETA-99]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-5.0.0-BETA-99]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:825) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:812) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [PacketUtil.class:1.10.2-5.0.0-BETA-99]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:134) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

Consequently, boolean value `event.getCause().first(Player.class).isPresent();` always false.
Version API: 5.0.0-snapshot, SpongeVanilla 99 and SpongeForge 1655

**Comment by gabizou** [comment]
For starters, you're never checking that the cause has a `Player` object in the first place, so naturally you'll be getting an exception because the player was not included. Second, you can use `@First Player player` as a method argument in your listener method and Sponge's event filtering will automatically filter players in for you. This issue sounds more about "Players aren't added to causes correctly on player death for `DropItemEvent.Destruct`.

**Comment by Azatik** [comment]
@gabizou I used `@First Player player` - event it never works.
Code:
```
    @Listener
    public void onDropItem(DropItemEvent.Destruct event, @First Player player) {
        logger = getLogger();
        logger.info("EventDropItem.Destruct cause:" + "\n" + event.getCause().toString());
        logger.info(player.getName());
    }
```

**Comment by gabizou** [comment]
Because again, you have to consider that it's an `EntitySpawnCause`.

**Comment by Azatik** [comment]
What does it mean?

**Comment by gabizou** [comment]
It means you need to unwrap the `EntitySpawnCause` and check that it's a `Player`.

**Comment by Azatik** [comment]
How unwrap the `EntitySpawnCause`?

**Comment by Azatik** [comment]
I done it.
I used code:
```
    @Listener
    public void onDropItem(DropItemEvent.Destruct event) {
        Optional<EntitySpawnCause> spawnType = event.getCause().first(EntitySpawnCause.class);
        if (spawnType.isPresent()) {
            EntitySpawnCause cause = spawnType.get();
            if ( cause.getEntity().getType().equals(EntityTypes.PLAYER)) {
                Player player = (Player) cause.getEntity();
                logger = getLogger();
                logger.info("EventDropItem.Destruct cause:" + "\n" + event.getCause().toString());
                logger.info("Player: " + player.getName());
            }
        }
    }
```

**Comment by gabizou** [comment]
You should just add a method parameter annotated as such:
```java
@Listener
public void onDropItem(DropItemEvent.Destruct event, @Root EntitySpawnCause cause) {
  if (cause.getEntity() instanceof Player) {
    Player player // more more more
  }
}
