### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by OblivionNW** [SpongePowered/SpongeCommon#878]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod ([SERVER] SpongeForge-1.8.9-1890-4.2.0-BETA-1653.jar)
  Java8CheckerCoremod (Pixelmon-1.8.9-4.2.7-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/9/16 12:28 AM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
    at org.spongepowered.common.event.CauseTracker.updateTickBlock(CauseTracker.java:1112)
    at net.minecraft.world.WorldServer.redirect$onUpdateBlockTick$0(WorldServer.java:394)
    at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:488)
    at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:465)
    at net.minecraft.block.BlockFalling.func_176204_a(BlockFalling.java:34)
    at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1157)
    at net.minecraft.world.World.func_175685_c(World.java:1343)
    at net.minecraft.world.World.func_175722_b(World.java:409)
    at net.minecraft.world.World.markAndNotifyNeighbors(World.java:1228)
    at org.spongepowered.common.event.CauseTracker.markAndNotifyBlockPost(CauseTracker.java:1232)
    at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:918)
    at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:416)
    at org.spongepowered.common.event.CauseTracker.postTrackBlock(CauseTracker.java:394)
    at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1103)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:330)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at org.spongepowered.common.event.CauseTracker.updateTickBlock(CauseTracker.java:1112)
    at net.minecraft.world.WorldServer.redirect$onUpdateBlockTick$0(WorldServer.java:394)
    at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:488)
    at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:465)
    at net.minecraft.block.BlockFalling.func_176204_a(BlockFalling.java:34)

-- Block being updated --
Details:
    Block: minecraft:gravel
    Block location: World: (5590,62,-2166), Chunk: (at 6,3,10 in 349,-136; contains blocks 5584,0,-2176 to 5599,255,-2161), Region: (10,-5; contains chunks 320,-160 to 351,-129, blocks 5120,0,-2560 to 5631,255,-2049)
Stacktrace:
    at org.spongepowered.common.event.CauseTracker.notifyBlockOfStateChange(CauseTracker.java:1157)
    at net.minecraft.world.World.func_175685_c(World.java:1343)
    at net.minecraft.world.World.func_175722_b(World.java:409)
    at net.minecraft.world.World.markAndNotifyNeighbors(World.java:1228)
    at org.spongepowered.common.event.CauseTracker.markAndNotifyBlockPost(CauseTracker.java:1232)
    at org.spongepowered.common.event.CauseTracker.handleBlockCaptures(CauseTracker.java:918)
    at org.spongepowered.common.event.CauseTracker.handlePostTickCaptures(CauseTracker.java:416)
    at org.spongepowered.common.event.CauseTracker.postTrackBlock(CauseTracker.java:394)
    at org.spongepowered.common.event.CauseTracker.randomTickBlock(CauseTracker.java:1103)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:330)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:221)
```

**Comment by Zidane** [comment]
1.8.9 is no longer supported.
