### ISSUE TITLE
[1.10.2] Chunks fail to save

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#879]
```
[12:46:29] [Server thread/ERROR]: Couldn't save chunk; already in use by another instance of Minecraft?
net.minecraft.world.MinecraftException: The save folder for world ./Main/Main is being accessed from another location, aborting
        at net.minecraft.world.storage.SaveHandler.func_75762_c(SaveHandler.java:96) ~[azy.class:?]
        at net.minecraft.world.World.func_72906_B(World.java:3428) ~[aid.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:167) ~[atj.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:267) [lr.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:201) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by DarkArc** [comment]
With a brand new world folder, this exception occurs when the server shuts down:
```
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_91]
        at net.minecraft.world.storage.SaveHandler.saveDimensionAndOtherData(SaveHandler.java:157) ~[azy.class:?]
        at net.minecraft.world.storage.SaveHandler.handler$onSaveWorldInfoWithPlayerAfterTagSet$0(SaveHandler.java:94) ~[azy.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:138) ~[azy.class:?]
        at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75755_a(AnvilSaveHandler.java:40) ~[azv.class:?]
        at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1055) ~[ls.class:?]
        at net.minecraft.world.WorldServerMulti.func_73042_a(WorldServerMulti.java:96) ~[lo.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1004) ~[ls.class:?]
        at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:494) ~[WorldManager.class:1.10.2-2052-5.0.0-BETA-1667]
        at org.spongepowered.common.world.WorldManager.unloadWorld(WorldManager.java:468) ~[WorldManager.class:1.10.2-2052-5.0.0-BETA-1667]
        at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:152) ~[DimensionManager.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:407) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeForge/commit/11167bd5b8ed60fe7abb657cb26f742024887336
