### ISSUE TITLE
getAchievementData() throws NoSuchElementException from Optional

### ISSUE THREAD

**Issue by jkcclemens** [SpongePowered/SpongeCommon#886]
```kotlin
this.game.commandManager.register(
    this,
    CommandSpec.builder()
        .executor { src, args ->
            if (src !is Player) {
                src.sendMessage(Text.of("Go away, console."))
                return@executor CommandResult.empty()
            }
            src.sendMessage(Text.of("You have ${src.achievementData.keys.size} achievements"))
            CommandResult.success()
        }
        .build(),
    "achievementcount"
)
```
```
[18:48:58 ERROR] [Sponge]: Error occurred while executing command 'achievementcount' for source EntityPlayerMP['jkcclemens'/302, l='world', x=-78.67, y=113.00, z=213.48]: No value present
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_92]
        at org.spongepowered.api.entity.living.player.User.getAchievementData(User.java:82) ~[User.class:1.10.2-5.0.0-BETA-100]
        at me.kyleclemens.spongejni.SpongeJNI$construction$1.execute(SpongeJNI.kt:59) ~[SpongeJNI$construction$1.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:332) ~[CommandSpec.class:1.10.2-5.0.0-BETA-100]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-5.0.0-BETA-100]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:274) [SpongeCommandManager.class:1.10.2-5.0.0-BETA-100]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:82) [bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:825) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:812) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:118) [PacketUtil.class:1.10.2-5.0.0-BETA-100]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(SourceFile:39) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:134) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```
```
> sponge version
[18:54:32 INFO]: SpongeVanilla
    Minecraft: 1.10.2
    SpongeAPI: 5.0.0-SNAPSHOT-d11a7b4
    SpongeVanilla: 1.10.2-5.0.0-BETA-100
```

**Comment by gabizou** [comment]
Look at #8. Achievements and Statistics aren't implemented.
