### ISSUE TITLE
[1.8.9] Error on get JoinData.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#898]
```
java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_92]
    at org.spongepowered.common.data.processor.multi.entity.JoinDataProcessor.getValues(JoinDataProcessor.java:68) ~[JoinDataProcessor.class:?]
    at org.spongepowered.common.data.processor.multi.entity.JoinDataProcessor.getValues(JoinDataProcessor.java:45) ~[JoinDataProcessor.class:?]
    at org.spongepowered.common.data.processor.common.AbstractMultiDataSingleTargetProcessor.from(AbstractMultiDataSingleTargetProcessor.java:76) ~[AbstractMultiDataSingleTargetProcessor.class:?]
    at org.spongepowered.common.data.util.DataProcessorDelegate.from(DataProcessorDelegate.java:94) ~[DataProcessorDelegate.class:?]
    at net.minecraft.entity.Entity.get(Entity.java:71) ~[Entity.class:?]
    at au.id.rleach.easyspawn.EasySpawn.onFirstJoin(EasySpawn.java:30) ~[EasySpawn.class:?]
    at org.spongepowered.common.event.listener.LoginListener_EasySpawn_onFirstJoin1.handle(Unknown Source) ~[?:?]
    at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:?]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201) [SpongeModEventManager.class:?]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242) [SpongeModEventManager.class:?]
    at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214) [SpongeModEventManager.class:?]
    at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:129) [SpongeImpl.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:223) [ServerConfigurationManager.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:242) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:142) [NetworkDispatcher.class:?]
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:65) [FMLNetworkHandler.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137) [NetHandlerLoginServer.class:?]
    at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64) [NetHandlerLoginServer.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:310) [NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:204) [NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:800) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:365) [DedicatedServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[01:36:05] [Server thread/INFO]: ryan_the_leach[/127.0.0.1:57505] logged in with entity id 204 in world(0) at (-227.5, 65.0, 173.5)
```

Github'd stacktrace:
- SpongeCommon
- https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/multi/entity/JoinDataProcessor.java#L68
- https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/multi/entity/JoinDataProcessor.java#L45
- https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/common/AbstractMultiDataSingleTargetProcessor.java#L76
- https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/util/DataProcessorDelegate.java#L94
- EasySpawn
- https://github.com/ryantheleach/EasySpawn/blob/master/src/main/java/au/id/rleach/easyspawn/EasySpawn.java#L30

The only code you need to be able to trigger this is.

```
    @Listener
    public void onFirstJoin(ClientConnectionEvent.Login event){
        Optional<JoinData> joinData = event.getTargetUser().get(JoinData.class);
    }
```

**Comment by bloodmc** [comment]
@ryantheleach Does this happen in 1.10.2+? If not, close ticket.

**Comment by bloodmc** [comment]
I don't have this issue in GP 1.10.2 which uses JoinData fine.
