### ISSUE TITLE
[Bleeding] AffectEntityEvent::filterEntities causes UnsupportedOperationException

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#913]
##Duplicates: https://github.com/SpongePowered/SpongeCommon/issues/896

Attempting to use https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/entity/AffectEntityEvent.java#L94 AffectEntityEvent::filterEntities

causes an UnsupportedOperationException.

Tested on SpongeForge https://github.com/SpongePowered/SpongeForge/commit/3e842c8e8a39669044ebebea967d0086176d4f48

```
[04:32:51] [Server thread/ERROR] [Sponge]: Could not pass SpawnEntityEvent$Impl to Plugin{id=modwiztesting.modwiztesting, name=Modwiztesting, version=1.0-SNAPSHOT, source=C:\c\Sponge\SpongeForge-bleeding\build\classes\production\modwiztesting_main}
java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(AbstractList.java:161) ~[?:1.8.0_92]
	at java.util.AbstractList$Itr.remove(AbstractList.java:374) ~[?:1.8.0_92]
	at org.spongepowered.api.event.entity.AffectEntityEvent.filterEntities(AffectEntityEvent.java:101) ~[AffectEntityEvent.class:?]
	at modwiztesting.modwiztesting.Modwiztesting.onSpawn(Modwiztesting.java:24) ~[Modwiztesting.class:?]
	at org.spongepowered.common.event.listener.SpawnEntityEventListener_Modwiztesting_onSpawn1.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:349) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:332) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:377) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:362) [SpongeModEventManager.class:?]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) [SpongeImpl.class:?]
	at org.spongepowered.common.event.tracking.phase.TrackingPhase.spawnEntityOrCapture(TrackingPhase.java:290) [TrackingPhase.class:?]
	at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:497) [CauseTracker.class:?]
	at net.minecraft.world.WorldServer.spawnEntityInWorld(WorldServer.java:1006) [WorldServer.class:?]
	at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:530) [WorldServer.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:228) [WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:772) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

**Comment by gabizou** [comment]
This is properly fixed in https://github.com/SpongePowered/SpongeCommon/commit/ad9aa8641d465419f0685c69f8f3fd694bc59d83

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/1c061c43e389c7171807c59b3d0500eb5afbc0ce
