### ISSUE TITLE
SpongeBanBuilder should accept a ban without a reason

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeCommon#929]
Creating a ban without a reason causes a precondition to fail
```java
Ban.of(player.getProfile());
```
Results in
```
java.lang.IllegalStateException: Reason cannot be null!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-17.0.jar:?]
	at org.spongepowered.common.ban.SpongeBanBuilder.build(SpongeBanBuilder.java:123) ~[SpongeBanBuilder.class:?]
	at org.spongepowered.api.util.ban.Ban.of(Ban.java:61) ~[Ban.class:?]
```
Using dev version on commit 9dc74b3693f19f10eb4e841f3723da0dd38d80ca

**Comment by ST-DDT** [comment]
[`SpongeBanBuilder#reason : Optional<Text>`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/ban/SpongeBanBuilder.java#L56) is not initialized.

The line
````java
 private Optional<Text> reason;
````
should be changed to 
````java
 private Optional<Text> reason = Optional.empty();
````
