### ISSUE TITLE
PlayerIDTable in level_sponge is triggering profile UUID lookups

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#958]
```
[20:18:55] [pool-3-thread-6/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@43efa2a4[id=8b963d6a-0925-3fc6-b29f-cb2b2ead80bc,name=,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
    at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) ~[YggdrasilMinecraftSessionService.class:?]
    at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:168) ~[YggdrasilMinecraftSessionService.class:?]
    at net.minecraft.server.management.PlayerProfileCache.lookupByIds(PlayerProfileCache.java:251) ~[PlayerProfileCache.class:?]
    at net.minecraft.server.management.PlayerProfileCache.getOrLookupByIds(PlayerProfileCache.java:286) ~[PlayerProfileCache.class:?]
    at org.spongepowered.common.profile.query.Query.fromUniqueIds(Query.java:70) ~[Query.class:?]
    at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:64) ~[UniqueIdQuery$SingleGet.class:?]
    at org.spongepowered.common.profile.query.UniqueIdQuery$SingleGet.call(UniqueIdQuery.java:45) ~[UniqueIdQuery$SingleGet.class:?]
    at org.spongepowered.api.util.Functional.lambda$asyncFailableFuture$2(Functional.java:165) ~[Functional.class:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

Affected the Minecon booth. Only critical bug.

**Comment by Zidane** [comment]
@bloodmc 

This can be triggered by using a World that has a Player ID table in the level_sponge data and you have no username/user cache files. Delete all of those, set your server to offline mode, and fire it up. It WILL start kicking off an exception quite similar to the above.

We need to be making sure that when a server is offline, no requests ever go to Mojang.

**Comment by dualspiral** [comment]
@Zidane @bloodmc Just make sure that if the BungeeCord/Proxy module is on, then you're still making the requests, but only if a spoofed UUID has been passed to the game (as it is possible to have the BungeeCord module on but log in without spoofing your UUID)

**Comment by ziceptor** [comment]
Maybe it's useful
https://github.com/SpongePowered/SpongeForge/issues/843

But the error appeared again and I don't know how to fix it.

**Comment by GershonR** [comment]
Any news on this?

**Comment by ziceptor** [comment]
@Zidane @kashike I figured it out. This is happening after migrating the configuration files to the new server. In particular due to the presence of PEX in the config IDs of the players. Error disappear after the player accesses to the server.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/1db378a1277ce1b91e3ee6bdc03fca7c06245d1a
