### ISSUE TITLE
[1.10.2] /toggledownfall is broken

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#959]
When I execute `/toggledownfall` on latest bleeding SV or SF it seems like nothing happens. I think it will get toggled again immediately after command execution for some reason:

```
[21:22:13] [Server thread/ERROR] [STDERR]: java.lang.Exception: Stack trace
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.lang.Thread.dumpStack(Thread.java:1329)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.storage.WorldInfo.setRaining(WorldInfo.java:321)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.command.CommandToggleDownfall.redirect$onToggleDownfall$0(CommandToggleDownfall.java:43)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.command.CommandToggleDownfall.execute(CommandToggleDownfall.java:37)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:98)
[21:22:13] [Server thread/ERROR] [STDERR]:  at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:143)
[21:22:13] [Server thread/ERROR] [STDERR]:  at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:129)
[21:22:13] [Server thread/ERROR] [STDERR]:  at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333)
[21:22:13] [Server thread/ERROR] [STDERR]:  at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:82)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:946)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:924)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8)
[21:22:13] [Server thread/ERROR] [STDERR]:  at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:122)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$0(PacketThreadUtil.java:39)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15)
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.util.Util.runTask(Util.java:16)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:140)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:399)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:543)
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.lang.Thread.run(Thread.java:745)
[21:22:13] [Server thread/INFO]: [Minecrell: Toggled downfall]
[21:22:13] [Server thread/ERROR] [STDERR]: java.lang.Exception: Stack trace
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.lang.Thread.dumpStack(Thread.java:1329)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.storage.WorldInfo.setRaining(WorldInfo.java:321)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.World.updateWeather(World.java:2408)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.WorldServer.updateWeather(WorldServer.java:1258)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.World.tick(World.java:2314)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.world.WorldServer.tick(WorldServer.java:170)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:168)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:399)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
[21:22:13] [Server thread/ERROR] [STDERR]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:543)
[21:22:13] [Server thread/ERROR] [STDERR]:  at java.lang.Thread.run(Thread.java:745)
```

**Comment by stephan-gh** [comment]
Doesn't happen on latest SV anymore.
